#!/bin/bash
set -euo pipefail

# Portable in-place sed (macOS uses -i '', Linux uses -i)
sedi() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

SPEC_URL="${SPEC_URL:-https://raw.githubusercontent.com/square/connect-api-specification/master/api.json}"

echo "==> Fetching Square OpenAPI spec..."
curl -sS -o api.json "$SPEC_URL"
echo "    Downloaded $(wc -c < api.json | tr -d ' ') bytes"

echo "==> Running openapi-generator..."
openapi-generator generate \
  -i api.json \
  -g rust \
  --library reqwest \
  --skip-validate-spec \
  --additional-properties=packageName=autogen-squareup,supportAsync=true,supportMiddleware=true \
  -o . \
  2>&1 | tail -5

echo "==> Cleaning up generated files we don't need..."
rm -f .travis.yml git_push.sh

echo "==> Applying post-generation fixes..."

# Fix 1: models::models:: double prefix in multipart API files (generator bug)
echo "    Fixing models::models:: double prefix..."
sedi 's/models::models::/models::/g' \
  src/apis/catalog_api.rs \
  src/apis/disputes_api.rs \
  src/apis/invoices_api.rs

# Fix 2: param_value.to_string() type inference failure in multipart form code
echo "    Fixing multipart to_string() type inference..."
sedi 's/param_value\.to_string()/serde_json::to_string(\&param_value).unwrap_or_default()/g' \
  src/apis/catalog_api.rs \
  src/apis/disputes_api.rs \
  src/apis/invoices_api.rs

# Fix 3: Missing vendor_id path parameter in update_vendor()
echo "    Fixing missing vendor_id parameter in update_vendor..."
sedi 's/pub async fn update_vendor(configuration: \&configuration::Configuration, update_vendor_request: models::UpdateVendorRequest)/pub async fn update_vendor(configuration: \&configuration::Configuration, vendor_id: \&str, update_vendor_request: models::UpdateVendorRequest)/' \
  src/apis/vendors_api.rs

# Fix 4: Missing CatalogModifierToggleOverrideType (spec references but never defines it)
echo "    Creating missing CatalogModifierToggleOverrideType enum..."
if ! grep -q 'catalog_modifier_toggle_override_type' src/models/mod.rs; then
  cat >> src/models/mod.rs <<'MODEOF'
pub mod catalog_modifier_toggle_override_type;
pub use self::catalog_modifier_toggle_override_type::CatalogModifierToggleOverrideType;
MODEOF
fi

cat > src/models/catalog_modifier_toggle_override_type.rs <<'TYPEEOF'
/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogModifierToggleOverrideType : Indicates whether a modifier list can be applied to a catalog item.
/// Defines the possible values for a `CatalogModifierToggleOverrideType` field.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogModifierToggleOverrideType {
    #[serde(rename = "DO_NOT_USE")]
    DoNotUse,
    #[serde(rename = "NOT_SET")]
    NotSet,
    #[serde(rename = "YES")]
    Yes,
    #[serde(rename = "NO")]
    No,
}

impl Default for CatalogModifierToggleOverrideType {
    fn default() -> CatalogModifierToggleOverrideType {
        Self::DoNotUse
    }
}
TYPEEOF

# Fix 5: AppFeeAllocation and CurrencyExchange are referenced by the spec but
# never defined (as of the 2026-07-15 release). Square's own SDKs type these
# fields as `unknown`, so fall back to serde_json::Value.
echo "    Replacing undefined AppFeeAllocation/CurrencyExchange with serde_json::Value..."
UNDEFINED_TYPE_FILES=$(grep -Erl 'models::(AppFeeAllocation|CurrencyExchange)' src/models || true)
if [ -n "$UNDEFINED_TYPE_FILES" ]; then
  sedi 's/models::AppFeeAllocation/serde_json::Value/g; s/models::CurrencyExchange/serde_json::Value/g' $UNDEFINED_TYPE_FILES
fi

# Fix 6: ErrorCode enum is missing codes the live API returns. Square's spec
# omits some codes from the ErrorCode enum definition even though the API
# returns them (e.g. ISSUER_INSTALLMENT_ERROR appears only in an
# x-endpoint-errors vendor extension on POST /v2/payments). Without a
# catch-all, one undocumented code fails deserialization of the entire
# response. Guarded by tests/error_code_test.rs.
echo "    Patching ErrorCode enum (missing codes + serde(other) catch-all)..."
python3 - <<'PYEOF'
path = "src/models/error_code.rs"
src = open(path).read()

variants = ""
if '"ISSUER_INSTALLMENT_ERROR"' not in src:
    variants += '    #[serde(rename = "ISSUER_INSTALLMENT_ERROR")]\n    IssuerInstallmentError,\n'
if "serde(other" not in src:
    variants += (
        '    /// Catch-all for error codes the published Square spec does not declare.\n'
        '    #[serde(other, rename = "UNKNOWN")]\n'
        '    Unknown,\n'
    )
if variants:
    enum_start = src.index("pub enum ErrorCode {")
    enum_end = src.index("\n}", enum_start) + 1  # position of closing brace line
    src = src[:enum_end] + variants + src[enum_end:]

arms = ""
if "Self::IssuerInstallmentError =>" not in src:
    arms += '            Self::IssuerInstallmentError => write!(f, "ISSUER_INSTALLMENT_ERROR"),\n'
if "Self::Unknown =>" not in src:
    arms += '            Self::Unknown => write!(f, "UNKNOWN"),\n'
if arms:
    display_start = src.index("impl std::fmt::Display for ErrorCode {")
    match_start = src.index("match self {", display_start)
    line_end = src.index("\n", match_start) + 1
    src = src[:line_end] + arms + src[line_end:]

open(path, "w").write(src)
PYEOF

# Fix 7: Re-apply feature gates to apis/mod.rs
echo "    Re-applying feature gates to apis/mod.rs..."
apply_gate() {
  local mod_name="$1" feature="$2"
  sedi "s/^pub mod ${mod_name};/#[cfg(feature = \"${feature}\")]\\"$'\n'"pub mod ${mod_name};/" src/apis/mod.rs
}

apply_gate apple_pay_api apple-pay
apply_gate bank_accounts_api bank-accounts
apply_gate booking_custom_attributes_api booking-custom-attributes
apply_gate bookings_api bookings
apply_gate cards_api cards
apply_gate cash_drawers_api cash-drawers
apply_gate catalog_api catalog
apply_gate channels_api channels
apply_gate checkout_api checkout
apply_gate customer_custom_attributes_api customer-custom-attributes
apply_gate customer_groups_api customer-groups
apply_gate customer_segments_api customer-segments
apply_gate customers_api customers
apply_gate devices_api devices
apply_gate disputes_api disputes
apply_gate employees_api employees
apply_gate events_api events
apply_gate gift_card_activities_api gift-card-activities
apply_gate gift_cards_api gift-cards
apply_gate inventory_api inventory
apply_gate invoices_api invoices
apply_gate labor_api labor
apply_gate location_custom_attributes_api location-custom-attributes
apply_gate locations_api locations
apply_gate loyalty_api loyalty
apply_gate merchant_custom_attributes_api merchant-custom-attributes
apply_gate merchants_api merchants
apply_gate mobile_authorization_api mobile-authorization
apply_gate o_auth_api oauth
apply_gate order_custom_attributes_api order-custom-attributes
apply_gate orders_api orders
apply_gate payments_api payments
apply_gate payouts_api payouts
apply_gate refunds_api refunds
apply_gate sites_api sites
apply_gate snippets_api snippets
apply_gate subscriptions_api subscriptions
apply_gate team_api team
apply_gate terminal_api terminal
apply_gate transactions_api transactions
apply_gate transfer_order_api transfer-order
apply_gate v1_transactions_api v1-transactions
apply_gate vendors_api vendors
apply_gate webhook_subscriptions_api webhook-subscriptions

echo "==> Verifying compilation..."
cargo check

echo "==> Done. Review changes with: git diff"
