/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccumulateLoyaltyPointsRequest : Represents an [AccumulateLoyaltyPoints](api-endpoint:Loyalty-AccumulateLoyaltyPoints) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccumulateLoyaltyPointsRequest {
    #[serde(rename = "accumulate_points")]
    pub accumulate_points: Box<models::LoyaltyEventAccumulatePoints>,
    /// A unique string that identifies the `AccumulateLoyaltyPoints` request.  Keys can be any valid string but must be unique for every request.
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    /// The [location](entity:Location) where the purchase was made.
    #[serde(rename = "location_id")]
    pub location_id: String,
}

impl AccumulateLoyaltyPointsRequest {
    /// Represents an [AccumulateLoyaltyPoints](api-endpoint:Loyalty-AccumulateLoyaltyPoints) request.
    pub fn new(accumulate_points: models::LoyaltyEventAccumulatePoints, idempotency_key: String, location_id: String) -> AccumulateLoyaltyPointsRequest {
        AccumulateLoyaltyPointsRequest {
            accumulate_points: Box::new(accumulate_points),
            idempotency_key,
            location_id,
        }
    }
}

