/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BankAccount : Represents a bank account. For more information about  linking a bank account to a Square account, see  [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankAccount {
    /// The unique, Square-issued identifier for the bank account.
    #[serde(rename = "id")]
    pub id: String,
    /// The last few digits of the account number.
    #[serde(rename = "account_number_suffix")]
    pub account_number_suffix: String,
    #[serde(rename = "country")]
    pub country: models::Country,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "account_type")]
    pub account_type: models::BankAccountType,
    /// Name of the account holder. This name must match the name  on the targeted bank account record.
    #[serde(rename = "holder_name")]
    pub holder_name: String,
    /// Primary identifier for the bank. For more information, see  [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
    #[serde(rename = "primary_bank_identification_number")]
    pub primary_bank_identification_number: String,
    /// Secondary identifier for the bank. For more information, see  [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
    #[serde(rename = "secondary_bank_identification_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secondary_bank_identification_number: Option<Option<String>>,
    /// Reference identifier that will be displayed to UK bank account owners when collecting direct debit authorization. Only required for UK bank accounts.
    #[serde(rename = "debit_mandate_reference_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub debit_mandate_reference_id: Option<Option<String>>,
    /// Client-provided identifier for linking the banking account to an entity in a third-party system (for example, a bank account number or a user identifier).
    #[serde(rename = "reference_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Option<String>>,
    /// The location to which the bank account belongs.
    #[serde(rename = "location_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::BankAccountStatus,
    /// Indicates whether it is possible for Square to send money to this bank account.
    #[serde(rename = "creditable")]
    pub creditable: bool,
    /// Indicates whether it is possible for Square to take money from this  bank account.
    #[serde(rename = "debitable")]
    pub debitable: bool,
    /// A Square-assigned, unique identifier for the bank account based on the account information. The account fingerprint can be used to compare account entries and determine if the they represent the same real-world bank account.
    #[serde(rename = "fingerprint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<Option<String>>,
    /// The current version of the `BankAccount`.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// Read only. Name of actual financial institution.  For example \"Bank of America\".
    #[serde(rename = "bank_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<Option<String>>,
}

impl BankAccount {
    /// Represents a bank account. For more information about  linking a bank account to a Square account, see  [Bank Accounts API](https://developer.squareup.com/docs/bank-accounts-api).
    pub fn new(id: String, account_number_suffix: String, country: models::Country, currency: models::Currency, account_type: models::BankAccountType, holder_name: String, primary_bank_identification_number: String, status: models::BankAccountStatus, creditable: bool, debitable: bool) -> BankAccount {
        BankAccount {
            id,
            account_number_suffix,
            country,
            currency,
            account_type,
            holder_name,
            primary_bank_identification_number,
            secondary_bank_identification_number: None,
            debit_mandate_reference_id: None,
            reference_id: None,
            location_id: None,
            status,
            creditable,
            debitable,
            fingerprint: None,
            version: None,
            bank_name: None,
        }
    }
}

