/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteCatalogObjectsRequest {
    /// The IDs of the CatalogObjects to be deleted. When an object is deleted, other objects in the graph that depend on that object will be deleted as well (for example, deleting a CatalogItem will delete its CatalogItemVariation.
    #[serde(rename = "object_ids")]
    pub object_ids: Vec<String>,
}

impl BatchDeleteCatalogObjectsRequest {
    pub fn new(object_ids: Vec<String>) -> BatchDeleteCatalogObjectsRequest {
        BatchDeleteCatalogObjectsRequest {
            object_ids,
        }
    }
}

