/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchRetrieveInventoryCountsRequest {
    /// The filter to return results by `CatalogObject` ID. The filter is applicable only when set.  The default is null.
    #[serde(rename = "catalog_object_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub catalog_object_ids: Option<Option<Vec<String>>>,
    /// The filter to return results by `Location` ID. This filter is applicable only when set. The default is null.
    #[serde(rename = "location_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_ids: Option<Option<Vec<String>>>,
    /// The filter to return results with their `calculated_at` value after the given time as specified in an RFC 3339 timestamp. The default value is the UNIX epoch of (`1970-01-01T00:00:00Z`).
    #[serde(rename = "updated_after", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_after: Option<Option<String>>,
    /// A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for the original query.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information.
    #[serde(rename = "cursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Option<String>>,
    /// The filter to return results by `InventoryState`. The filter is only applicable when set. Ignored are untracked states of `NONE`, `SOLD`, and `UNLINKED_RETURN`. The default is null.
    #[serde(rename = "states", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub states: Option<Option<Vec<models::InventoryState>>>,
    /// The number of [records](entity:InventoryCount) to return.
    #[serde(rename = "limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Option<i32>>,
}

impl BatchRetrieveInventoryCountsRequest {
    pub fn new() -> BatchRetrieveInventoryCountsRequest {
        BatchRetrieveInventoryCountsRequest {
            catalog_object_ids: None,
            location_ids: None,
            updated_after: None,
            cursor: None,
            states: None,
            limit: None,
        }
    }
}

