/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchRetrieveOrdersRequest : Defines the fields that are included in requests to the `BatchRetrieveOrders` endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchRetrieveOrdersRequest {
    /// The ID of the location for these orders. This field is optional: omit it to retrieve orders within the scope of the current authorization's merchant ID.
    #[serde(rename = "location_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Option<String>>,
    /// The IDs of the orders to retrieve. A maximum of 100 orders can be retrieved per request.
    #[serde(rename = "order_ids")]
    pub order_ids: Vec<String>,
}

impl BatchRetrieveOrdersRequest {
    /// Defines the fields that are included in requests to the `BatchRetrieveOrders` endpoint.
    pub fn new(order_ids: Vec<String>) -> BatchRetrieveOrdersRequest {
        BatchRetrieveOrdersRequest {
            location_id: None,
            order_ids,
        }
    }
}

