/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BulkRetrieveChannelsRequestConstants {
    #[serde(rename = "MAX_BATCH_SIZE")]
    MaxBatchSize,

}

impl std::fmt::Display for BulkRetrieveChannelsRequestConstants {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MaxBatchSize => write!(f, "MAX_BATCH_SIZE"),
        }
    }
}

impl Default for BulkRetrieveChannelsRequestConstants {
    fn default() -> BulkRetrieveChannelsRequestConstants {
        Self::MaxBatchSize
    }
}

