/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkDeleteBookingCustomAttributesRequest : Represents a [BulkDeleteBookingCustomAttributes](api-endpoint:BookingCustomAttributes-BulkDeleteBookingCustomAttributes) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkDeleteBookingCustomAttributesRequest {
    /// A map containing 1 to 25 individual Delete requests. For each request, provide an arbitrary ID that is unique for this `BulkDeleteBookingCustomAttributes` request and the information needed to delete a custom attribute.
    #[serde(rename = "values")]
    pub values: std::collections::HashMap<String, models::BookingCustomAttributeDeleteRequest>,
}

impl BulkDeleteBookingCustomAttributesRequest {
    /// Represents a [BulkDeleteBookingCustomAttributes](api-endpoint:BookingCustomAttributes-BulkDeleteBookingCustomAttributes) request.
    pub fn new(values: std::collections::HashMap<String, models::BookingCustomAttributeDeleteRequest>) -> BulkDeleteBookingCustomAttributesRequest {
        BulkDeleteBookingCustomAttributesRequest {
            values,
        }
    }
}

