/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkCreateTeamMembersResponse : Represents a response from a bulk create request containing the created `TeamMember` objects or error messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkCreateTeamMembersResponse {
    /// The successfully created `TeamMember` objects. Each key is the `idempotency_key` that maps to the `CreateTeamMemberRequest`.
    #[serde(rename = "team_members", skip_serializing_if = "Option::is_none")]
    pub team_members: Option<std::collections::HashMap<String, models::CreateTeamMemberResponse>>,
    /// The errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl BulkCreateTeamMembersResponse {
    /// Represents a response from a bulk create request containing the created `TeamMember` objects or error messages.
    pub fn new() -> BulkCreateTeamMembersResponse {
        BulkCreateTeamMembersResponse {
            team_members: None,
            errors: None,
        }
    }
}

