/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkRetrieveVendorsResponse : Represents an output from a call to [BulkRetrieveVendors](api-endpoint:Vendors-BulkRetrieveVendors).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkRetrieveVendorsResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The set of [RetrieveVendorResponse](entity:RetrieveVendorResponse) objects encapsulating successfully retrieved [Vendor](entity:Vendor) objects or error responses for failed attempts. The set is represented by  a collection of `Vendor`-ID/`Vendor`-object or `Vendor`-ID/error-object pairs.
    #[serde(rename = "responses", skip_serializing_if = "Option::is_none")]
    pub responses: Option<std::collections::HashMap<String, models::RetrieveVendorResponse>>,
}

impl BulkRetrieveVendorsResponse {
    /// Represents an output from a call to [BulkRetrieveVendors](api-endpoint:Vendors-BulkRetrieveVendors).
    pub fn new() -> BulkRetrieveVendorsResponse {
        BulkRetrieveVendorsResponse {
            errors: None,
            responses: None,
        }
    }
}

