/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkUpdateCustomersResponse : Defines the fields included in the response body from the [BulkUpdateCustomers](api-endpoint:Customers-BulkUpdateCustomers) endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpdateCustomersResponse {
    /// A map of responses that correspond to individual update requests, represented by key-value pairs.  Each key is the customer ID that was specified for an update request and each value is the corresponding response. If the request succeeds, the value is the updated customer profile. If the request fails, the value contains any errors that occurred during the request.
    #[serde(rename = "responses", skip_serializing_if = "Option::is_none")]
    pub responses: Option<std::collections::HashMap<String, models::UpdateCustomerResponse>>,
    /// Any top-level errors that prevented the bulk operation from running.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl BulkUpdateCustomersResponse {
    /// Defines the fields included in the response body from the [BulkUpdateCustomers](api-endpoint:Customers-BulkUpdateCustomers) endpoint.
    pub fn new() -> BulkUpdateCustomersResponse {
        BulkUpdateCustomersResponse {
            responses: None,
            errors: None,
        }
    }
}

