/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkCreateTeamMembersRequest : Represents a bulk create request for `TeamMember` objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkCreateTeamMembersRequest {
    /// The data used to create the `TeamMember` objects. Each key is the `idempotency_key` that maps to the `CreateTeamMemberRequest`. The maximum number of create objects is 25.  If you include a team member's `wage_setting`, you must provide `job_id` for each job assignment. To get job IDs, call [ListJobs](api-endpoint:Team-ListJobs).
    #[serde(rename = "team_members")]
    pub team_members: std::collections::HashMap<String, models::CreateTeamMemberRequest>,
}

impl BulkCreateTeamMembersRequest {
    /// Represents a bulk create request for `TeamMember` objects.
    pub fn new(team_members: std::collections::HashMap<String, models::CreateTeamMemberRequest>) -> BulkCreateTeamMembersRequest {
        BulkCreateTeamMembersRequest {
            team_members,
        }
    }
}

