/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkUpsertLocationCustomAttributesRequest : Represents a [BulkUpsertLocationCustomAttributes](api-endpoint:LocationCustomAttributes-BulkUpsertLocationCustomAttributes) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpsertLocationCustomAttributesRequest {
    /// A map containing 1 to 25 individual upsert requests. For each request, provide an arbitrary ID that is unique for this `BulkUpsertLocationCustomAttributes` request and the information needed to create or update a custom attribute.
    #[serde(rename = "values")]
    pub values: std::collections::HashMap<String, models::BulkUpsertLocationCustomAttributesRequestLocationCustomAttributeUpsertRequest>,
}

impl BulkUpsertLocationCustomAttributesRequest {
    /// Represents a [BulkUpsertLocationCustomAttributes](api-endpoint:LocationCustomAttributes-BulkUpsertLocationCustomAttributes) request.
    pub fn new(values: std::collections::HashMap<String, models::BulkUpsertLocationCustomAttributesRequestLocationCustomAttributeUpsertRequest>) -> BulkUpsertLocationCustomAttributesRequest {
        BulkUpsertLocationCustomAttributesRequest {
            values,
        }
    }
}

