/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkUpdateVendorsRequest : Represents an input to a call to [BulkUpdateVendors](api-endpoint:Vendors-BulkUpdateVendors).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpdateVendorsRequest {
    /// A set of [UpdateVendorRequest](entity:UpdateVendorRequest) objects encapsulating to-be-updated [Vendor](entity:Vendor) objects. The set is represented by  a collection of `Vendor`-ID/`UpdateVendorRequest`-object pairs.
    #[serde(rename = "vendors")]
    pub vendors: std::collections::HashMap<String, models::UpdateVendorRequest>,
}

impl BulkUpdateVendorsRequest {
    /// Represents an input to a call to [BulkUpdateVendors](api-endpoint:Vendors-BulkUpdateVendors).
    pub fn new(vendors: std::collections::HashMap<String, models::UpdateVendorRequest>) -> BulkUpdateVendorsRequest {
        BulkUpdateVendorsRequest {
            vendors,
        }
    }
}

