/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse : Represents a response for an individual upsert request in a [BulkUpsertCustomerCustomAttributes](api-endpoint:CustomerCustomAttributes-BulkUpsertCustomerCustomAttributes) operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse {
    /// The ID of the customer profile associated with the custom attribute.
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "custom_attribute", skip_serializing_if = "Option::is_none")]
    pub custom_attribute: Option<Box<models::CustomAttribute>>,
    /// Any errors that occurred while processing the individual request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl BulkUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse {
    /// Represents a response for an individual upsert request in a [BulkUpsertCustomerCustomAttributes](api-endpoint:CustomerCustomAttributes-BulkUpsertCustomerCustomAttributes) operation.
    pub fn new() -> BulkUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse {
        BulkUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse {
            customer_id: None,
            custom_attribute: None,
            errors: None,
        }
    }
}

