/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessAppointmentSettingsCancellationPolicy : The category of the seller’s cancellation policy.
/// The category of the seller’s cancellation policy.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BusinessAppointmentSettingsCancellationPolicy {
    #[serde(rename = "CANCELLATION_TREATED_AS_NO_SHOW")]
    CancellationTreatedAsNoShow,
    #[serde(rename = "CUSTOM_POLICY")]
    CustomPolicy,

}

impl std::fmt::Display for BusinessAppointmentSettingsCancellationPolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CancellationTreatedAsNoShow => write!(f, "CANCELLATION_TREATED_AS_NO_SHOW"),
            Self::CustomPolicy => write!(f, "CUSTOM_POLICY"),
        }
    }
}

impl Default for BusinessAppointmentSettingsCancellationPolicy {
    fn default() -> BusinessAppointmentSettingsCancellationPolicy {
        Self::CancellationTreatedAsNoShow
    }
}

