/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType : Types of daily appointment limits.
/// Types of daily appointment limits.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType {
    #[serde(rename = "PER_TEAM_MEMBER")]
    PerTeamMember,
    #[serde(rename = "PER_LOCATION")]
    PerLocation,

}

impl std::fmt::Display for BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PerTeamMember => write!(f, "PER_TEAM_MEMBER"),
            Self::PerLocation => write!(f, "PER_LOCATION"),
        }
    }
}

impl Default for BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType {
    fn default() -> BusinessAppointmentSettingsMaxAppointmentsPerDayLimitType {
        Self::PerTeamMember
    }
}

