/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashPaymentDetails : Stores details about a cash payment. Contains only non-confidential information. For more information, see  [Take Cash Payments](https://developer.squareup.com/docs/payments-api/take-payments/cash-payments).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashPaymentDetails {
    #[serde(rename = "buyer_supplied_money")]
    pub buyer_supplied_money: Box<models::Money>,
    #[serde(rename = "change_back_money", skip_serializing_if = "Option::is_none")]
    pub change_back_money: Option<Box<models::Money>>,
}

impl CashPaymentDetails {
    /// Stores details about a cash payment. Contains only non-confidential information. For more information, see  [Take Cash Payments](https://developer.squareup.com/docs/payments-api/take-payments/cash-payments).
    pub fn new(buyer_supplied_money: models::Money) -> CashPaymentDetails {
        CashPaymentDetails {
            buyer_supplied_money: Box::new(buyer_supplied_money),
            change_back_money: None,
        }
    }
}

