/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogModifierListModifierType : Defines the type of `CatalogModifierList`.
/// Defines the type of `CatalogModifierList`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogModifierListModifierType {
    #[serde(rename = "LIST")]
    List,
    #[serde(rename = "TEXT")]
    Text,

}

impl std::fmt::Display for CatalogModifierListModifierType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::List => write!(f, "LIST"),
            Self::Text => write!(f, "TEXT"),
        }
    }
}

impl Default for CatalogModifierListModifierType {
    fn default() -> CatalogModifierListModifierType {
        Self::List
    }
}

