/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogQuickAmountType : Determines the type of a specific Quick Amount.
/// Determines the type of a specific Quick Amount.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogQuickAmountType {
    #[serde(rename = "QUICK_AMOUNT_TYPE_MANUAL")]
    QuickAmountTypeManual,
    #[serde(rename = "QUICK_AMOUNT_TYPE_AUTO")]
    QuickAmountTypeAuto,

}

impl std::fmt::Display for CatalogQuickAmountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::QuickAmountTypeManual => write!(f, "QUICK_AMOUNT_TYPE_MANUAL"),
            Self::QuickAmountTypeAuto => write!(f, "QUICK_AMOUNT_TYPE_AUTO"),
        }
    }
}

impl Default for CatalogQuickAmountType {
    fn default() -> CatalogQuickAmountType {
        Self::QuickAmountTypeManual
    }
}

