/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogQuerySortedAttribute : The query expression to specify the key to sort search results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogQuerySortedAttribute {
    /// The attribute whose value is used as the sort key.
    #[serde(rename = "attribute_name")]
    pub attribute_name: String,
    /// The first attribute value to be returned by the query. Ascending sorts will return only objects with this value or greater, while descending sorts will return only objects with this value or less. If unset, start at the beginning (for ascending sorts) or end (for descending sorts).
    #[serde(rename = "initial_attribute_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub initial_attribute_value: Option<Option<String>>,
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<models::SortOrder>,
}

impl CatalogQuerySortedAttribute {
    /// The query expression to specify the key to sort search results.
    pub fn new(attribute_name: String) -> CatalogQuerySortedAttribute {
        CatalogQuerySortedAttribute {
            attribute_name,
            initial_attribute_value: None,
            sort_order: None,
        }
    }
}

