/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogModifierListSelectionType : Indicates whether a CatalogModifierList supports multiple selections.
/// Indicates whether a CatalogModifierList supports multiple selections.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogModifierListSelectionType {
    #[serde(rename = "SINGLE")]
    Single,
    #[serde(rename = "MULTIPLE")]
    Multiple,

}

impl std::fmt::Display for CatalogModifierListSelectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Single => write!(f, "SINGLE"),
            Self::Multiple => write!(f, "MULTIPLE"),
        }
    }
}

impl Default for CatalogModifierListSelectionType {
    fn default() -> CatalogModifierListSelectionType {
        Self::Single
    }
}

