/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogCustomAttributeDefinitionStringConfig : Configuration associated with Custom Attribute Definitions of type `STRING`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCustomAttributeDefinitionStringConfig {
    /// If true, each Custom Attribute instance associated with this Custom Attribute Definition must have a unique value within the seller's catalog. For example, this may be used for a value like a SKU that should not be duplicated within a seller's catalog. May not be modified after the definition has been created.
    #[serde(rename = "enforce_uniqueness", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enforce_uniqueness: Option<Option<bool>>,
}

impl CatalogCustomAttributeDefinitionStringConfig {
    /// Configuration associated with Custom Attribute Definitions of type `STRING`.
    pub fn new() -> CatalogCustomAttributeDefinitionStringConfig {
        CatalogCustomAttributeDefinitionStringConfig {
            enforce_uniqueness: None,
        }
    }
}

