/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogItemOptionValue : An enumerated value that can link a `CatalogItemVariation` to an item option as one of its item option values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogItemOptionValue {
    /// Unique ID of the associated item option.
    #[serde(rename = "item_option_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_option_id: Option<Option<String>>,
    /// Name of this item option value. This is a searchable attribute for use in applicable query filters.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// A human-readable description for the option value. This is a searchable attribute for use in applicable query filters.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The HTML-supported hex color for the item option (e.g., \"#ff8d4e85\"). Only displayed if `show_colors` is enabled on the parent `ItemOption`. When left unset, `color` defaults to white (\"#ffffff\") when `show_colors` is enabled on the parent `ItemOption`.
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    /// Determines where this option value appears in a list of option values.
    #[serde(rename = "ordinal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<Option<i32>>,
}

impl CatalogItemOptionValue {
    /// An enumerated value that can link a `CatalogItemVariation` to an item option as one of its item option values.
    pub fn new() -> CatalogItemOptionValue {
        CatalogItemOptionValue {
            item_option_id: None,
            name: None,
            description: None,
            color: None,
            ordinal: None,
        }
    }
}

