/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogSubscriptionPlan : Describes a subscription plan. A subscription plan represents what you want to sell in a subscription model, and includes references to each of the associated subscription plan variations. For more information, see [Subscription Plans and Variations](https://developer.squareup.com/docs/subscriptions-api/plans-and-variations).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogSubscriptionPlan {
    /// The name of the plan.
    #[serde(rename = "name")]
    pub name: String,
    /// A list of SubscriptionPhase containing the [SubscriptionPhase](entity:SubscriptionPhase) for this plan. This field it required. Not including this field will throw a REQUIRED_FIELD_MISSING error
    #[serde(rename = "phases", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phases: Option<Option<Vec<models::SubscriptionPhase>>>,
    /// The list of subscription plan variations available for this product
    #[serde(rename = "subscription_plan_variations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subscription_plan_variations: Option<Option<Vec<models::CatalogObject>>>,
    /// The list of IDs of `CatalogItems` that are eligible for subscription by this SubscriptionPlan's variations.
    #[serde(rename = "eligible_item_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub eligible_item_ids: Option<Option<Vec<String>>>,
    /// The list of IDs of `CatalogCategory` that are eligible for subscription by this SubscriptionPlan's variations.
    #[serde(rename = "eligible_category_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub eligible_category_ids: Option<Option<Vec<String>>>,
    /// If true, all items in the merchant's catalog are subscribable by this SubscriptionPlan.
    #[serde(rename = "all_items", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all_items: Option<Option<bool>>,
}

impl CatalogSubscriptionPlan {
    /// Describes a subscription plan. A subscription plan represents what you want to sell in a subscription model, and includes references to each of the associated subscription plan variations. For more information, see [Subscription Plans and Variations](https://developer.squareup.com/docs/subscriptions-api/plans-and-variations).
    pub fn new(name: String) -> CatalogSubscriptionPlan {
        CatalogSubscriptionPlan {
            name,
            phases: None,
            subscription_plan_variations: None,
            eligible_item_ids: None,
            eligible_category_ids: None,
            all_items: None,
        }
    }
}

