/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogItemOptionValueForItemVariation : A `CatalogItemOptionValue` links an item variation to an item option as an item option value. For example, a t-shirt item may offer a color option and a size option. An item option value would represent each variation of t-shirt: For example, \"Color:Red, Size:Small\" or \"Color:Blue, Size:Medium\".
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogItemOptionValueForItemVariation {
    /// The unique id of an item option.
    #[serde(rename = "item_option_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_option_id: Option<Option<String>>,
    /// The unique id of the selected value for the item option.
    #[serde(rename = "item_option_value_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_option_value_id: Option<Option<String>>,
}

impl CatalogItemOptionValueForItemVariation {
    /// A `CatalogItemOptionValue` links an item variation to an item option as an item option value. For example, a t-shirt item may offer a color option and a size option. An item option value would represent each variation of t-shirt: For example, \"Color:Red, Size:Small\" or \"Color:Blue, Size:Medium\".
    pub fn new() -> CatalogItemOptionValueForItemVariation {
        CatalogItemOptionValueForItemVariation {
            item_option_id: None,
            item_option_value_id: None,
        }
    }
}

