/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogCustomAttributeDefinition : Contains information defining a custom attribute. Custom attributes are intended to store additional information about a catalog object or to associate a catalog object with an entity in another system. Do not use custom attributes to store any sensitive information (personally identifiable information, card details, etc.). [Read more about custom attributes](https://developer.squareup.com/docs/catalog-api/add-custom-attributes)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCustomAttributeDefinition {
    #[serde(rename = "type")]
    pub r#type: models::CatalogCustomAttributeDefinitionType,
    ///  The name of this definition for API and seller-facing UI purposes. The name must be unique within the (merchant, application) pair. Required. May not be empty and may not exceed 255 characters. Can be modified after creation.
    #[serde(rename = "name")]
    pub name: String,
    /// Seller-oriented description of the meaning of this Custom Attribute, any constraints that the seller should observe, etc. May be displayed as a tooltip in Square UIs.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "source_application", skip_serializing_if = "Option::is_none")]
    pub source_application: Option<Box<models::SourceApplication>>,
    /// The set of `CatalogObject` types that this custom atttribute may be applied to. Currently, only `ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, and `CATEGORY` are allowed. At least one type must be included. See [CatalogObjectType](#type-catalogobjecttype) for possible values
    #[serde(rename = "allowed_object_types")]
    pub allowed_object_types: Vec<models::CatalogObjectType>,
    #[serde(rename = "seller_visibility", skip_serializing_if = "Option::is_none")]
    pub seller_visibility: Option<models::CatalogCustomAttributeDefinitionSellerVisibility>,
    #[serde(rename = "app_visibility", skip_serializing_if = "Option::is_none")]
    pub app_visibility: Option<models::CatalogCustomAttributeDefinitionAppVisibility>,
    #[serde(rename = "string_config", skip_serializing_if = "Option::is_none")]
    pub string_config: Option<Box<models::CatalogCustomAttributeDefinitionStringConfig>>,
    #[serde(rename = "number_config", skip_serializing_if = "Option::is_none")]
    pub number_config: Option<Box<models::CatalogCustomAttributeDefinitionNumberConfig>>,
    #[serde(rename = "selection_config", skip_serializing_if = "Option::is_none")]
    pub selection_config: Option<Box<models::CatalogCustomAttributeDefinitionSelectionConfig>>,
    /// The number of custom attributes that reference this custom attribute definition. Set by the server in response to a ListCatalog request with `include_counts` set to `true`.  If the actual count is greater than 100, `custom_attribute_usage_count` will be set to `100`.
    #[serde(rename = "custom_attribute_usage_count", skip_serializing_if = "Option::is_none")]
    pub custom_attribute_usage_count: Option<i32>,
    /// The name of the desired custom attribute key that can be used to access the custom attribute value on catalog objects. Cannot be modified after the custom attribute definition has been created. Must be between 1 and 60 characters, and may only contain the characters `[a-zA-Z0-9_-]`.
    #[serde(rename = "key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub key: Option<Option<String>>,
}

impl CatalogCustomAttributeDefinition {
    /// Contains information defining a custom attribute. Custom attributes are intended to store additional information about a catalog object or to associate a catalog object with an entity in another system. Do not use custom attributes to store any sensitive information (personally identifiable information, card details, etc.). [Read more about custom attributes](https://developer.squareup.com/docs/catalog-api/add-custom-attributes)
    pub fn new(r#type: models::CatalogCustomAttributeDefinitionType, name: String, allowed_object_types: Vec<models::CatalogObjectType>) -> CatalogCustomAttributeDefinition {
        CatalogCustomAttributeDefinition {
            r#type,
            name,
            description: None,
            source_application: None,
            allowed_object_types,
            seller_visibility: None,
            app_visibility: None,
            string_config: None,
            number_config: None,
            selection_config: None,
            custom_attribute_usage_count: None,
            key: None,
        }
    }
}

