/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogEcomSeoData : SEO data for for a seller's Square Online store.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogEcomSeoData {
    /// The SEO title used for the Square Online store.
    #[serde(rename = "page_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_title: Option<Option<String>>,
    /// The SEO description used for the Square Online store.
    #[serde(rename = "page_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page_description: Option<Option<String>>,
    /// The SEO permalink used for the Square Online store.
    #[serde(rename = "permalink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permalink: Option<Option<String>>,
}

impl CatalogEcomSeoData {
    /// SEO data for for a seller's Square Online store.
    pub fn new() -> CatalogEcomSeoData {
        CatalogEcomSeoData {
            page_title: None,
            page_description: None,
            permalink: None,
        }
    }
}

