/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogObjectBatch : A batch of catalog objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogObjectBatch {
    /// A list of CatalogObjects belonging to this batch.
    #[serde(rename = "objects")]
    pub objects: Vec<models::CatalogObject>,
}

impl CatalogObjectBatch {
    /// A batch of catalog objects.
    pub fn new(objects: Vec<models::CatalogObject>) -> CatalogObjectBatch {
        CatalogObjectBatch {
            objects,
        }
    }
}

