/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogQuerySet : The query filter to return the search result(s) by exact match of the specified `attribute_name` and any of the `attribute_values`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogQuerySet {
    /// The name of the attribute to be searched. Matching of the attribute name is exact.
    #[serde(rename = "attribute_name")]
    pub attribute_name: String,
    /// The desired values of the search attribute. Matching of the attribute values is exact and case insensitive. A maximum of 250 values may be searched in a request.
    #[serde(rename = "attribute_values")]
    pub attribute_values: Vec<String>,
}

impl CatalogQuerySet {
    /// The query filter to return the search result(s) by exact match of the specified `attribute_name` and any of the `attribute_values`.
    pub fn new(attribute_name: String, attribute_values: Vec<String>) -> CatalogQuerySet {
        CatalogQuerySet {
            attribute_name,
            attribute_values,
        }
    }
}

