/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogCategory : A category to which a `CatalogItem` instance belongs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCategory {
    /// The category name. This is a searchable attribute for use in applicable query filters, and its value length is of Unicode code points.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The IDs of images associated with this `CatalogCategory` instance. Currently these images are not displayed by Square, but are free to be displayed in 3rd party applications.
    #[serde(rename = "image_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "category_type", skip_serializing_if = "Option::is_none")]
    pub category_type: Option<models::CatalogCategoryType>,
    #[serde(rename = "parent_category", skip_serializing_if = "Option::is_none")]
    pub parent_category: Option<Box<models::CatalogObjectCategory>>,
    /// Indicates whether a category is a top level category, which does not have any parent_category.
    #[serde(rename = "is_top_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_top_level: Option<Option<bool>>,
    /// A list of IDs representing channels, such as a Square Online site, where the category can be made visible.
    #[serde(rename = "channels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Option<Vec<String>>>,
    /// The IDs of the `CatalogAvailabilityPeriod` objects associated with the category.
    #[serde(rename = "availability_period_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub availability_period_ids: Option<Option<Vec<String>>>,
    /// Indicates whether the category is visible (`true`) or hidden (`false`) on all of the seller's Square Online sites.
    #[serde(rename = "online_visibility", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub online_visibility: Option<Option<bool>>,
    /// The top-level category in a category hierarchy.
    #[serde(rename = "root_category", skip_serializing_if = "Option::is_none")]
    pub root_category: Option<String>,
    #[serde(rename = "ecom_seo_data", skip_serializing_if = "Option::is_none")]
    pub ecom_seo_data: Option<Box<models::CatalogEcomSeoData>>,
    /// The path from the category to its root category. The first node of the path is the parent of the category and the last is the root category. The path is empty if the category is a root category.
    #[serde(rename = "path_to_root", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path_to_root: Option<Option<Vec<models::CategoryPathToRootNode>>>,
}

impl CatalogCategory {
    /// A category to which a `CatalogItem` instance belongs.
    pub fn new() -> CatalogCategory {
        CatalogCategory {
            name: None,
            image_ids: None,
            category_type: None,
            parent_category: None,
            is_top_level: None,
            channels: None,
            availability_period_ids: None,
            online_visibility: None,
            root_category: None,
            ecom_seo_data: None,
            path_to_root: None,
        }
    }
}

