/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogObjectType : Possible types of CatalogObjects returned from the catalog, each containing type-specific properties in the `*_data` field corresponding to the specified object type.
/// Possible types of CatalogObjects returned from the catalog, each containing type-specific properties in the `*_data` field corresponding to the specified object type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogObjectType {
    #[serde(rename = "ITEM")]
    Item,
    #[serde(rename = "IMAGE")]
    Image,
    #[serde(rename = "CATEGORY")]
    Category,
    #[serde(rename = "ITEM_VARIATION")]
    ItemVariation,
    #[serde(rename = "TAX")]
    Tax,
    #[serde(rename = "DISCOUNT")]
    Discount,
    #[serde(rename = "MODIFIER_LIST")]
    ModifierList,
    #[serde(rename = "MODIFIER")]
    Modifier,
    #[serde(rename = "PRICING_RULE")]
    PricingRule,
    #[serde(rename = "PRODUCT_SET")]
    ProductSet,
    #[serde(rename = "TIME_PERIOD")]
    TimePeriod,
    #[serde(rename = "MEASUREMENT_UNIT")]
    MeasurementUnit,
    #[serde(rename = "SUBSCRIPTION_PLAN_VARIATION")]
    SubscriptionPlanVariation,
    #[serde(rename = "ITEM_OPTION")]
    ItemOption,
    #[serde(rename = "ITEM_OPTION_VAL")]
    ItemOptionVal,
    #[serde(rename = "CUSTOM_ATTRIBUTE_DEFINITION")]
    CustomAttributeDefinition,
    #[serde(rename = "QUICK_AMOUNTS_SETTINGS")]
    QuickAmountsSettings,
    #[serde(rename = "SUBSCRIPTION_PLAN")]
    SubscriptionPlan,
    #[serde(rename = "AVAILABILITY_PERIOD")]
    AvailabilityPeriod,

}

impl std::fmt::Display for CatalogObjectType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Item => write!(f, "ITEM"),
            Self::Image => write!(f, "IMAGE"),
            Self::Category => write!(f, "CATEGORY"),
            Self::ItemVariation => write!(f, "ITEM_VARIATION"),
            Self::Tax => write!(f, "TAX"),
            Self::Discount => write!(f, "DISCOUNT"),
            Self::ModifierList => write!(f, "MODIFIER_LIST"),
            Self::Modifier => write!(f, "MODIFIER"),
            Self::PricingRule => write!(f, "PRICING_RULE"),
            Self::ProductSet => write!(f, "PRODUCT_SET"),
            Self::TimePeriod => write!(f, "TIME_PERIOD"),
            Self::MeasurementUnit => write!(f, "MEASUREMENT_UNIT"),
            Self::SubscriptionPlanVariation => write!(f, "SUBSCRIPTION_PLAN_VARIATION"),
            Self::ItemOption => write!(f, "ITEM_OPTION"),
            Self::ItemOptionVal => write!(f, "ITEM_OPTION_VAL"),
            Self::CustomAttributeDefinition => write!(f, "CUSTOM_ATTRIBUTE_DEFINITION"),
            Self::QuickAmountsSettings => write!(f, "QUICK_AMOUNTS_SETTINGS"),
            Self::SubscriptionPlan => write!(f, "SUBSCRIPTION_PLAN"),
            Self::AvailabilityPeriod => write!(f, "AVAILABILITY_PERIOD"),
        }
    }
}

impl Default for CatalogObjectType {
    fn default() -> CatalogObjectType {
        Self::Item
    }
}

