/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoryPathToRootNode : A node in the path from a retrieved category to its root node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryPathToRootNode {
    /// The category's ID.
    #[serde(rename = "category_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Option<String>>,
    /// The category's name.
    #[serde(rename = "category_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_name: Option<Option<String>>,
}

impl CategoryPathToRootNode {
    /// A node in the path from a retrieved category to its root node.
    pub fn new() -> CategoryPathToRootNode {
        CategoryPathToRootNode {
            category_id: None,
            category_name: None,
        }
    }
}

