/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeTiming : Supported timings when a pending change, as an action, takes place to a subscription.
/// Supported timings when a pending change, as an action, takes place to a subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeTiming {
    #[serde(rename = "IMMEDIATE")]
    Immediate,
    #[serde(rename = "END_OF_BILLING_CYCLE")]
    EndOfBillingCycle,

}

impl std::fmt::Display for ChangeTiming {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Immediate => write!(f, "IMMEDIATE"),
            Self::EndOfBillingCycle => write!(f, "END_OF_BILLING_CYCLE"),
        }
    }
}

impl Default for ChangeTiming {
    fn default() -> ChangeTiming {
        Self::Immediate
    }
}

