/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChargeRequestAdditionalRecipient : Represents an additional recipient (other than the merchant) entitled to a portion of the tender. Support is currently limited to USD, CAD and GBP currencies
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChargeRequestAdditionalRecipient {
    /// The location ID for a recipient (other than the merchant) receiving a portion of the tender.
    #[serde(rename = "location_id")]
    pub location_id: String,
    /// The description of the additional recipient.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "amount_money")]
    pub amount_money: Box<models::Money>,
}

impl ChargeRequestAdditionalRecipient {
    /// Represents an additional recipient (other than the merchant) entitled to a portion of the tender. Support is currently limited to USD, CAD and GBP currencies
    pub fn new(location_id: String, description: String, amount_money: models::Money) -> ChargeRequestAdditionalRecipient {
        ChargeRequestAdditionalRecipient {
            location_id,
            description,
            amount_money: Box::new(amount_money),
        }
    }
}

