/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutLocationSettingsBranding {
    #[serde(rename = "header_type", skip_serializing_if = "Option::is_none")]
    pub header_type: Option<models::CheckoutLocationSettingsBrandingHeaderType>,
    /// The HTML-supported hex color for the button on the checkout page (for example, \"#FFFFFF\").
    #[serde(rename = "button_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub button_color: Option<Option<String>>,
    #[serde(rename = "button_shape", skip_serializing_if = "Option::is_none")]
    pub button_shape: Option<models::CheckoutLocationSettingsBrandingButtonShape>,
}

impl CheckoutLocationSettingsBranding {
    pub fn new() -> CheckoutLocationSettingsBranding {
        CheckoutLocationSettingsBranding {
            header_type: None,
            button_color: None,
            button_shape: None,
        }
    }
}

