/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBankAccountRequest : Request object for linking a bank account to a Square account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBankAccountRequest {
    /// Unique ID. For more information, see the [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    /// The ID of the source that represents the bank account information to be stored. This field accepts the payment token created by WebSDK
    #[serde(rename = "source_id")]
    pub source_id: String,
    /// The ID of the customer associated with the bank account to be stored.
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
}

impl CreateBankAccountRequest {
    /// Request object for linking a bank account to a Square account
    pub fn new(idempotency_key: String, source_id: String) -> CreateBankAccountRequest {
        CreateBankAccountRequest {
            idempotency_key,
            source_id,
            customer_id: None,
        }
    }
}

