/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateInventoryAdjustmentReasonRequest : Represents an input to a call to [CreateInventoryAdjustmentReason](api-endpoint:Inventory-CreateInventoryAdjustmentReason).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInventoryAdjustmentReasonRequest {
    /// A client-supplied, universally unique identifier to make this [CreateInventoryAdjustmentReason](api-endpoint:Inventory-CreateInventoryAdjustmentReason) request idempotent.
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    #[serde(rename = "adjustment_reason")]
    pub adjustment_reason: Box<models::InventoryAdjustmentReason>,
}

impl CreateInventoryAdjustmentReasonRequest {
    /// Represents an input to a call to [CreateInventoryAdjustmentReason](api-endpoint:Inventory-CreateInventoryAdjustmentReason).
    pub fn new(idempotency_key: String, adjustment_reason: models::InventoryAdjustmentReason) -> CreateInventoryAdjustmentReasonRequest {
        CreateInventoryAdjustmentReasonRequest {
            idempotency_key,
            adjustment_reason: Box::new(adjustment_reason),
        }
    }
}

