/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateShiftResponse : The response to a request to create a `Shift`. The response contains the created `Shift` object and might contain a set of `Error` objects if the request resulted in errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateShiftResponse {
    #[serde(rename = "shift", skip_serializing_if = "Option::is_none")]
    pub shift: Option<Box<models::Shift>>,
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl CreateShiftResponse {
    /// The response to a request to create a `Shift`. The response contains the created `Shift` object and might contain a set of `Error` objects if the request resulted in errors.
    pub fn new() -> CreateShiftResponse {
        CreateShiftResponse {
            shift: None,
            errors: None,
        }
    }
}

