/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBookingResponse {
    #[serde(rename = "booking", skip_serializing_if = "Option::is_none")]
    pub booking: Option<Box<models::Booking>>,
    /// Errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl CreateBookingResponse {
    pub fn new() -> CreateBookingResponse {
        CreateBookingResponse {
            booking: None,
            errors: None,
        }
    }
}

