/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateGiftCardRequest : Represents a [CreateGiftCard](api-endpoint:GiftCards-CreateGiftCard) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGiftCardRequest {
    /// A unique identifier for this request, used to ensure idempotency. For more information,  see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    /// The ID of the [location](entity:Location) where the gift card should be registered for  reporting purposes. Gift cards can be redeemed at any of the seller's locations.
    #[serde(rename = "location_id")]
    pub location_id: String,
    #[serde(rename = "gift_card")]
    pub gift_card: Box<models::GiftCard>,
}

impl CreateGiftCardRequest {
    /// Represents a [CreateGiftCard](api-endpoint:GiftCards-CreateGiftCard) request.
    pub fn new(idempotency_key: String, location_id: String, gift_card: models::GiftCard) -> CreateGiftCardRequest {
        CreateGiftCardRequest {
            idempotency_key,
            location_id,
            gift_card: Box::new(gift_card),
        }
    }
}

