/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateDisputeEvidenceTextResponse : Defines the fields in a `CreateDisputeEvidenceText` response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDisputeEvidenceTextResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Box<models::DisputeEvidence>>,
}

impl CreateDisputeEvidenceTextResponse {
    /// Defines the fields in a `CreateDisputeEvidenceText` response.
    pub fn new() -> CreateDisputeEvidenceTextResponse {
        CreateDisputeEvidenceTextResponse {
            errors: None,
            evidence: None,
        }
    }
}

