/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateGiftCardResponse : A response that contains a `GiftCard`. The response might contain a set of `Error` objects if the request resulted in errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGiftCardResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "gift_card", skip_serializing_if = "Option::is_none")]
    pub gift_card: Option<Box<models::GiftCard>>,
}

impl CreateGiftCardResponse {
    /// A response that contains a `GiftCard`. The response might contain a set of `Error` objects if the request resulted in errors.
    pub fn new() -> CreateGiftCardResponse {
        CreateGiftCardResponse {
            errors: None,
            gift_card: None,
        }
    }
}

