/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBookingCustomAttributeDefinitionResponse : Represents a [CreateBookingCustomAttributeDefinition](api-endpoint:BookingCustomAttributes-CreateBookingCustomAttributeDefinition) response. Either `custom_attribute_definition` or `errors` is present in the response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBookingCustomAttributeDefinitionResponse {
    #[serde(rename = "custom_attribute_definition", skip_serializing_if = "Option::is_none")]
    pub custom_attribute_definition: Option<Box<models::CustomAttributeDefinition>>,
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl CreateBookingCustomAttributeDefinitionResponse {
    /// Represents a [CreateBookingCustomAttributeDefinition](api-endpoint:BookingCustomAttributes-CreateBookingCustomAttributeDefinition) response. Either `custom_attribute_definition` or `errors` is present in the response.
    pub fn new() -> CreateBookingCustomAttributeDefinitionResponse {
        CreateBookingCustomAttributeDefinitionResponse {
            custom_attribute_definition: None,
            errors: None,
        }
    }
}

