/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerFilter : Represents the filtering criteria in a [search query](entity:CustomerQuery) that defines how to filter customer profiles returned in [SearchCustomers](api-endpoint:Customers-SearchCustomers) results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerFilter {
    #[serde(rename = "creation_source", skip_serializing_if = "Option::is_none")]
    pub creation_source: Option<Box<models::CustomerCreationSourceFilter>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<Box<models::TimeRange>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Box<models::TimeRange>>,
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<Box<models::CustomerTextFilter>>,
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Box<models::CustomerTextFilter>>,
    #[serde(rename = "reference_id", skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Box<models::CustomerTextFilter>>,
    #[serde(rename = "group_ids", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Box<models::FilterValue>>,
    #[serde(rename = "custom_attribute", skip_serializing_if = "Option::is_none")]
    pub custom_attribute: Option<Box<models::CustomerCustomAttributeFilters>>,
    #[serde(rename = "segment_ids", skip_serializing_if = "Option::is_none")]
    pub segment_ids: Option<Box<models::FilterValue>>,
}

impl CustomerFilter {
    /// Represents the filtering criteria in a [search query](entity:CustomerQuery) that defines how to filter customer profiles returned in [SearchCustomers](api-endpoint:Customers-SearchCustomers) results.
    pub fn new() -> CustomerFilter {
        CustomerFilter {
            creation_source: None,
            created_at: None,
            updated_at: None,
            email_address: None,
            phone_number: None,
            reference_id: None,
            group_ids: None,
            custom_attribute: None,
            segment_ids: None,
        }
    }
}

