/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerInclusionExclusion : Indicates whether customers should be included in, or excluded from, the result set when they match the filtering criteria.
/// Indicates whether customers should be included in, or excluded from, the result set when they match the filtering criteria.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerInclusionExclusion {
    #[serde(rename = "INCLUDE")]
    Include,
    #[serde(rename = "EXCLUDE")]
    Exclude,

}

impl std::fmt::Display for CustomerInclusionExclusion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Include => write!(f, "INCLUDE"),
            Self::Exclude => write!(f, "EXCLUDE"),
        }
    }
}

impl Default for CustomerInclusionExclusion {
    fn default() -> CustomerInclusionExclusion {
        Self::Include
    }
}

