/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerCustomAttributeFilters : The custom attribute filters in a set of [customer filters](entity:CustomerFilter) used in a search query. Use this filter to search based on [custom attributes](entity:CustomAttribute) that are assigned to customer profiles. For more information, see [Search by custom attribute](https://developer.squareup.com/docs/customers-api/use-the-api/search-customers#search-by-custom-attribute).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCustomAttributeFilters {
    /// The custom attribute filters. Each filter must specify `key` and include the `filter` field with a type-specific filter, the `updated_at` field, or both. The provided keys must be unique within the list of custom attribute filters.
    #[serde(rename = "filters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Option<Vec<models::CustomerCustomAttributeFilter>>>,
}

impl CustomerCustomAttributeFilters {
    /// The custom attribute filters in a set of [customer filters](entity:CustomerFilter) used in a search query. Use this filter to search based on [custom attributes](entity:CustomAttribute) that are assigned to customer profiles. For more information, see [Search by custom attribute](https://developer.squareup.com/docs/customers-api/use-the-api/search-customers#search-by-custom-attribute).
    pub fn new() -> CustomerCustomAttributeFilters {
        CustomerCustomAttributeFilters {
            filters: None,
        }
    }
}

