/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerCreationSource : Indicates the method used to create the customer profile.
/// Indicates the method used to create the customer profile.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerCreationSource {
    #[serde(rename = "OTHER")]
    Other,
    #[serde(rename = "APPOINTMENTS")]
    Appointments,
    #[serde(rename = "COUPON")]
    Coupon,
    #[serde(rename = "DELETION_RECOVERY")]
    DeletionRecovery,
    #[serde(rename = "DIRECTORY")]
    Directory,
    #[serde(rename = "EGIFTING")]
    Egifting,
    #[serde(rename = "EMAIL_COLLECTION")]
    EmailCollection,
    #[serde(rename = "FEEDBACK")]
    Feedback,
    #[serde(rename = "IMPORT")]
    Import,
    #[serde(rename = "INVOICES")]
    Invoices,
    #[serde(rename = "LOYALTY")]
    Loyalty,
    #[serde(rename = "MARKETING")]
    Marketing,
    #[serde(rename = "MERGE")]
    Merge,
    #[serde(rename = "ONLINE_STORE")]
    OnlineStore,
    #[serde(rename = "INSTANT_PROFILE")]
    InstantProfile,
    #[serde(rename = "TERMINAL")]
    Terminal,
    #[serde(rename = "THIRD_PARTY")]
    ThirdParty,
    #[serde(rename = "THIRD_PARTY_IMPORT")]
    ThirdPartyImport,
    #[serde(rename = "UNMERGE_RECOVERY")]
    UnmergeRecovery,

}

impl std::fmt::Display for CustomerCreationSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Other => write!(f, "OTHER"),
            Self::Appointments => write!(f, "APPOINTMENTS"),
            Self::Coupon => write!(f, "COUPON"),
            Self::DeletionRecovery => write!(f, "DELETION_RECOVERY"),
            Self::Directory => write!(f, "DIRECTORY"),
            Self::Egifting => write!(f, "EGIFTING"),
            Self::EmailCollection => write!(f, "EMAIL_COLLECTION"),
            Self::Feedback => write!(f, "FEEDBACK"),
            Self::Import => write!(f, "IMPORT"),
            Self::Invoices => write!(f, "INVOICES"),
            Self::Loyalty => write!(f, "LOYALTY"),
            Self::Marketing => write!(f, "MARKETING"),
            Self::Merge => write!(f, "MERGE"),
            Self::OnlineStore => write!(f, "ONLINE_STORE"),
            Self::InstantProfile => write!(f, "INSTANT_PROFILE"),
            Self::Terminal => write!(f, "TERMINAL"),
            Self::ThirdParty => write!(f, "THIRD_PARTY"),
            Self::ThirdPartyImport => write!(f, "THIRD_PARTY_IMPORT"),
            Self::UnmergeRecovery => write!(f, "UNMERGE_RECOVERY"),
        }
    }
}

impl Default for CustomerCreationSource {
    fn default() -> CustomerCreationSource {
        Self::Other
    }
}

