/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerSortField : Specifies customer attributes as the sort key to customer profiles returned from a search.
/// Specifies customer attributes as the sort key to customer profiles returned from a search.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerSortField {
    #[serde(rename = "DEFAULT")]
    Default,
    #[serde(rename = "CREATED_AT")]
    CreatedAt,

}

impl std::fmt::Display for CustomerSortField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Default => write!(f, "DEFAULT"),
            Self::CreatedAt => write!(f, "CREATED_AT"),
        }
    }
}

impl Default for CustomerSortField {
    fn default() -> CustomerSortField {
        Self::Default
    }
}

