/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerDetails : Details about the customer making the payment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerDetails {
    /// Indicates whether the customer initiated the payment.
    #[serde(rename = "customer_initiated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_initiated: Option<Option<bool>>,
    /// Indicates that the seller keyed in payment details on behalf of the customer. This is used to flag a payment as Mail Order / Telephone Order (MOTO).
    #[serde(rename = "seller_keyed_in", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seller_keyed_in: Option<Option<bool>>,
}

impl CustomerDetails {
    /// Details about the customer making the payment.
    pub fn new() -> CustomerDetails {
        CustomerDetails {
            customer_initiated: None,
            seller_keyed_in: None,
        }
    }
}

