/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteShiftResponse : The response to a request to delete a `Shift`. The response might contain a set of  `Error` objects if the request resulted in errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteShiftResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl DeleteShiftResponse {
    /// The response to a request to delete a `Shift`. The response might contain a set of  `Error` objects if the request resulted in errors.
    pub fn new() -> DeleteShiftResponse {
        DeleteShiftResponse {
            errors: None,
        }
    }
}

