/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Destination : Information about the destination against which the payout was made.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Destination {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::DestinationType>,
    /// Square issued unique ID (also known as the instrument ID) associated with this destination.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl Destination {
    /// Information about the destination against which the payout was made.
    pub fn new() -> Destination {
        Destination {
            r#type: None,
            id: None,
        }
    }
}

