/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceDetails : Details about the device that took the payment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceDetails {
    /// The Square-issued ID of the device.
    #[serde(rename = "device_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Option<String>>,
    /// The Square-issued installation ID for the device.
    #[serde(rename = "device_installation_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_installation_id: Option<Option<String>>,
    /// The name of the device set by the seller.
    #[serde(rename = "device_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_name: Option<Option<String>>,
}

impl DeviceDetails {
    /// Details about the device that took the payment.
    pub fn new() -> DeviceDetails {
        DeviceDetails {
            device_id: None,
            device_installation_id: None,
            device_name: None,
        }
    }
}

