/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DigitalWalletDetails : Additional details about `WALLET` type payments. Contains only non-confidential information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DigitalWalletDetails {
    /// The status of the `WALLET` payment. The status can be `AUTHORIZED`, `CAPTURED`, `VOIDED`, or `FAILED`.
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// The brand used for the `WALLET` payment. The brand can be `CASH_APP`, `PAYPAY`, `ALIPAY`, `RAKUTEN_PAY`, `AU_PAY`, `D_BARAI`, `MERPAY`, `WECHAT_PAY` or `UNKNOWN`.
    #[serde(rename = "brand", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand: Option<Option<String>>,
    #[serde(rename = "cash_app_details", skip_serializing_if = "Option::is_none")]
    pub cash_app_details: Option<Box<models::CashAppDetails>>,
}

impl DigitalWalletDetails {
    /// Additional details about `WALLET` type payments. Contains only non-confidential information.
    pub fn new() -> DigitalWalletDetails {
        DigitalWalletDetails {
            status: None,
            brand: None,
            cash_app_details: None,
        }
    }
}

