/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DisableBankAccountResponse : Response object returned by `DisableBankAccount`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisableBankAccountResponse {
    #[serde(rename = "bank_account", skip_serializing_if = "Option::is_none")]
    pub bank_account: Option<Box<models::BankAccount>>,
    /// Information on errors encountered during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl DisableBankAccountResponse {
    /// Response object returned by `DisableBankAccount`.
    pub fn new() -> DisableBankAccountResponse {
        DisableBankAccountResponse {
            bank_account: None,
            errors: None,
        }
    }
}

