/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DisputedPayment : The payment the cardholder disputed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisputedPayment {
    /// Square-generated unique ID of the payment being disputed.
    #[serde(rename = "payment_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Option<String>>,
}

impl DisputedPayment {
    /// The payment the cardholder disputed.
    pub fn new() -> DisputedPayment {
        DisputedPayment {
            payment_id: None,
        }
    }
}

