/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisputeEvidenceDeletedEventData {
    /// Name of the affected dispute's type.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// ID of the affected dispute.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Box<models::DisputeEvidenceDeletedEventObject>>,
}

impl DisputeEvidenceDeletedEventData {
    pub fn new() -> DisputeEvidenceDeletedEventData {
        DisputeEvidenceDeletedEventData {
            r#type: None,
            id: None,
            object: None,
        }
    }
}

