/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FulfillmentFulfillmentLineItemApplication : The `line_item_application` describes what order line items this fulfillment applies to. It can be `ALL` or `ENTRY_LIST` with a supplied list of fulfillment entries.
/// The `line_item_application` describes what order line items this fulfillment applies to. It can be `ALL` or `ENTRY_LIST` with a supplied list of fulfillment entries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FulfillmentFulfillmentLineItemApplication {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "ENTRY_LIST")]
    EntryList,

}

impl std::fmt::Display for FulfillmentFulfillmentLineItemApplication {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "ALL"),
            Self::EntryList => write!(f, "ENTRY_LIST"),
        }
    }
}

impl Default for FulfillmentFulfillmentLineItemApplication {
    fn default() -> FulfillmentFulfillmentLineItemApplication {
        Self::All
    }
}

