/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FulfillmentShipmentDetails : Contains the details necessary to fulfill a shipment order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FulfillmentShipmentDetails {
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<Box<models::FulfillmentRecipient>>,
    /// The shipping carrier being used to ship this fulfillment (such as UPS, FedEx, or USPS).
    #[serde(rename = "carrier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub carrier: Option<Option<String>>,
    /// A note with additional information for the shipping carrier.
    #[serde(rename = "shipping_note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_note: Option<Option<String>>,
    /// A description of the type of shipping product purchased from the carrier (such as First Class, Priority, or Express).
    #[serde(rename = "shipping_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_type: Option<Option<String>>,
    /// The reference number provided by the carrier to track the shipment's progress.
    #[serde(rename = "tracking_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracking_number: Option<Option<String>>,
    /// A link to the tracking webpage on the carrier's website.
    #[serde(rename = "tracking_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tracking_url: Option<Option<String>>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when the shipment was requested. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "placed_at", skip_serializing_if = "Option::is_none")]
    pub placed_at: Option<String>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when this fulfillment was moved to the `RESERVED` state, which  indicates that preparation of this shipment has begun. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "in_progress_at", skip_serializing_if = "Option::is_none")]
    pub in_progress_at: Option<String>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when this fulfillment was moved to the `PREPARED` state, which indicates that the fulfillment is packaged. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "packaged_at", skip_serializing_if = "Option::is_none")]
    pub packaged_at: Option<String>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when the shipment is expected to be delivered to the shipping carrier. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "expected_shipped_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expected_shipped_at: Option<Option<String>>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when this fulfillment was moved to the `COMPLETED` state, which indicates that the fulfillment has been given to the shipping carrier. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "shipped_at", skip_serializing_if = "Option::is_none")]
    pub shipped_at: Option<String>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating the shipment was canceled. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "canceled_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub canceled_at: Option<Option<String>>,
    /// A description of why the shipment was canceled.
    #[serde(rename = "cancel_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<Option<String>>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when the shipment failed to be completed. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "failed_at", skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<String>,
    /// A description of why the shipment failed to be completed.
    #[serde(rename = "failure_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<Option<String>>,
}

impl FulfillmentShipmentDetails {
    /// Contains the details necessary to fulfill a shipment order.
    pub fn new() -> FulfillmentShipmentDetails {
        FulfillmentShipmentDetails {
            recipient: None,
            carrier: None,
            shipping_note: None,
            shipping_type: None,
            tracking_number: None,
            tracking_url: None,
            placed_at: None,
            in_progress_at: None,
            packaged_at: None,
            expected_shipped_at: None,
            shipped_at: None,
            canceled_at: None,
            cancel_reason: None,
            failed_at: None,
            failure_reason: None,
        }
    }
}

