/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FulfillmentPickupDetailsCurbsidePickupDetails : Specific details for curbside pickup.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FulfillmentPickupDetailsCurbsidePickupDetails {
    /// Specific details for curbside pickup, such as parking number and vehicle model.
    #[serde(rename = "curbside_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub curbside_details: Option<Option<String>>,
    /// The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when the buyer arrived and is waiting for pickup. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\").
    #[serde(rename = "buyer_arrived_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub buyer_arrived_at: Option<Option<String>>,
}

impl FulfillmentPickupDetailsCurbsidePickupDetails {
    /// Specific details for curbside pickup.
    pub fn new() -> FulfillmentPickupDetailsCurbsidePickupDetails {
        FulfillmentPickupDetailsCurbsidePickupDetails {
            curbside_details: None,
            buyer_arrived_at: None,
        }
    }
}

