/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetEmployeeWageResponse : A response to a request to get an `EmployeeWage`. The response contains the requested `EmployeeWage` objects and might contain a set of `Error` objects if the request resulted in errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEmployeeWageResponse {
    #[serde(rename = "employee_wage", skip_serializing_if = "Option::is_none")]
    pub employee_wage: Option<Box<models::EmployeeWage>>,
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl GetEmployeeWageResponse {
    /// A response to a request to get an `EmployeeWage`. The response contains the requested `EmployeeWage` objects and might contain a set of `Error` objects if the request resulted in errors.
    pub fn new() -> GetEmployeeWageResponse {
        GetEmployeeWageResponse {
            employee_wage: None,
            errors: None,
        }
    }
}

