/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPaymentRefundResponse : Defines the response returned by [GetRefund](api-endpoint:Refunds-GetPaymentRefund).  Note: If there are errors processing the request, the refund field might not be present or it might be present in a FAILED state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPaymentRefundResponse {
    /// Information about errors encountered during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "refund", skip_serializing_if = "Option::is_none")]
    pub refund: Option<Box<models::PaymentRefund>>,
}

impl GetPaymentRefundResponse {
    /// Defines the response returned by [GetRefund](api-endpoint:Refunds-GetPaymentRefund).  Note: If there are errors processing the request, the refund field might not be present or it might be present in a FAILED state.
    pub fn new() -> GetPaymentRefundResponse {
        GetPaymentRefundResponse {
            errors: None,
            refund: None,
        }
    }
}

