/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GiftCardActivityCreatedEvent : Published when a [gift card activity](entity:GiftCardActivity) is created.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiftCardActivityCreatedEvent {
    /// The ID of the Square seller associated with the event.
    #[serde(rename = "merchant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<Option<String>>,
    /// The type of event. For this event, the value is `gift_card.activity.created`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// The unique ID of the event, which is used for  [idempotency support](https://developer.squareup.com/docs/webhooks/step4manage#webhooks-best-practices).
    #[serde(rename = "event_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<Option<String>>,
    /// The timestamp of when the event was created, in RFC 3339 format.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GiftCardActivityCreatedEventData>>,
}

impl GiftCardActivityCreatedEvent {
    /// Published when a [gift card activity](entity:GiftCardActivity) is created.
    pub fn new() -> GiftCardActivityCreatedEvent {
        GiftCardActivityCreatedEvent {
            merchant_id: None,
            r#type: None,
            event_id: None,
            created_at: None,
            data: None,
        }
    }
}

