/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GiftCardActivityUnblock : Represents details about an `UNBLOCK` [gift card activity type](entity:GiftCardActivityType).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiftCardActivityUnblock {
    #[serde(rename = "reason")]
    pub reason: models::GiftCardActivityUnblockReason,
}

impl GiftCardActivityUnblock {
    /// Represents details about an `UNBLOCK` [gift card activity type](entity:GiftCardActivityType).
    pub fn new(reason: models::GiftCardActivityUnblockReason) -> GiftCardActivityUnblock {
        GiftCardActivityUnblock {
            reason,
        }
    }
}

