/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GiftCardCustomerUnlinkedEventObject : An object that contains the gift card and the customer ID associated with a  `gift_card.customer_linked` event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiftCardCustomerUnlinkedEventObject {
    #[serde(rename = "gift_card", skip_serializing_if = "Option::is_none")]
    pub gift_card: Option<Box<models::GiftCard>>,
    /// The ID of the unlinked [customer](entity:Customer).
    #[serde(rename = "unlinked_customer_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unlinked_customer_id: Option<Option<String>>,
}

impl GiftCardCustomerUnlinkedEventObject {
    /// An object that contains the gift card and the customer ID associated with a  `gift_card.customer_linked` event.
    pub fn new() -> GiftCardCustomerUnlinkedEventObject {
        GiftCardCustomerUnlinkedEventObject {
            gift_card: None,
            unlinked_customer_id: None,
        }
    }
}

