/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GiftCardCreatedEventData : The data associated with a `gift_card.created` event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiftCardCreatedEventData {
    /// The type of object affected by the event. For this event, the value is `gift_card`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// The ID of the new gift card.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Box<models::GiftCardCreatedEventObject>>,
}

impl GiftCardCreatedEventData {
    /// The data associated with a `gift_card.created` event.
    pub fn new() -> GiftCardCreatedEventData {
        GiftCardCreatedEventData {
            r#type: None,
            id: None,
            object: None,
        }
    }
}

