/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InventoryAdjustmentReasonId : Identifies a standard or custom inventory adjustment reason.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryAdjustmentReasonId {
    #[serde(rename = "type")]
    pub r#type: models::InventoryAdjustmentReasonIdType,
    /// The Square-generated ID of the custom adjustment reason. This field is only set when `type` is `CUSTOM`.
    #[serde(rename = "custom_reason_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_reason_id: Option<Option<String>>,
}

impl InventoryAdjustmentReasonId {
    /// Identifies a standard or custom inventory adjustment reason.
    pub fn new(r#type: models::InventoryAdjustmentReasonIdType) -> InventoryAdjustmentReasonId {
        InventoryAdjustmentReasonId {
            r#type,
            custom_reason_id: None,
        }
    }
}

