/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InventoryState : Indicates the state of a tracked item quantity in the lifecycle of goods.
/// Indicates the state of a tracked item quantity in the lifecycle of goods.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InventoryState {
    #[serde(rename = "CUSTOM")]
    Custom,
    #[serde(rename = "IN_STOCK")]
    InStock,
    #[serde(rename = "SOLD")]
    Sold,
    #[serde(rename = "RETURNED_BY_CUSTOMER")]
    ReturnedByCustomer,
    #[serde(rename = "RESERVED_FOR_SALE")]
    ReservedForSale,
    #[serde(rename = "SOLD_ONLINE")]
    SoldOnline,
    #[serde(rename = "ORDERED_FROM_VENDOR")]
    OrderedFromVendor,
    #[serde(rename = "RECEIVED_FROM_VENDOR")]
    ReceivedFromVendor,
    #[serde(rename = "IN_TRANSIT_TO")]
    InTransitTo,
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "WASTE")]
    Waste,
    #[serde(rename = "UNLINKED_RETURN")]
    UnlinkedReturn,
    #[serde(rename = "COMPOSED")]
    Composed,
    #[serde(rename = "DECOMPOSED")]
    Decomposed,
    #[serde(rename = "SUPPORTED_BY_NEWER_VERSION")]
    SupportedByNewerVersion,
    #[serde(rename = "IN_TRANSIT")]
    InTransit,

}

impl std::fmt::Display for InventoryState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Custom => write!(f, "CUSTOM"),
            Self::InStock => write!(f, "IN_STOCK"),
            Self::Sold => write!(f, "SOLD"),
            Self::ReturnedByCustomer => write!(f, "RETURNED_BY_CUSTOMER"),
            Self::ReservedForSale => write!(f, "RESERVED_FOR_SALE"),
            Self::SoldOnline => write!(f, "SOLD_ONLINE"),
            Self::OrderedFromVendor => write!(f, "ORDERED_FROM_VENDOR"),
            Self::ReceivedFromVendor => write!(f, "RECEIVED_FROM_VENDOR"),
            Self::InTransitTo => write!(f, "IN_TRANSIT_TO"),
            Self::None => write!(f, "NONE"),
            Self::Waste => write!(f, "WASTE"),
            Self::UnlinkedReturn => write!(f, "UNLINKED_RETURN"),
            Self::Composed => write!(f, "COMPOSED"),
            Self::Decomposed => write!(f, "DECOMPOSED"),
            Self::SupportedByNewerVersion => write!(f, "SUPPORTED_BY_NEWER_VERSION"),
            Self::InTransit => write!(f, "IN_TRANSIT"),
        }
    }
}

impl Default for InventoryState {
    fn default() -> InventoryState {
        Self::Custom
    }
}

