/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoicePaymentRequest : Represents a payment request for an [invoice](entity:Invoice). Invoices can specify a maximum of 13 payment requests, with up to 12 `INSTALLMENT` request types. For more information,  see [Configuring payment requests](https://developer.squareup.com/docs/invoices-api/create-publish-invoices#payment-requests).  Adding `INSTALLMENT` payment requests to an invoice requires an  [Invoices Plus subscription](https://developer.squareup.com/docs/invoices-api/overview#invoices-plus-subscription).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoicePaymentRequest {
    /// The Square-generated ID of the payment request in an [invoice](entity:Invoice).
    #[serde(rename = "uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uid: Option<Option<String>>,
    #[serde(rename = "request_method", skip_serializing_if = "Option::is_none")]
    pub request_method: Option<models::InvoiceRequestMethod>,
    #[serde(rename = "request_type", skip_serializing_if = "Option::is_none")]
    pub request_type: Option<models::InvoiceRequestType>,
    /// The due date (in the invoice's time zone) for the payment request, in `YYYY-MM-DD` format. This field is required to create a payment request. If an `automatic_payment_source` is defined for the request, Square charges the payment source on this date.  After this date, the invoice becomes overdue. For example, a payment `due_date` of 2021-03-09 with a `timezone` of America/Los\\_Angeles becomes overdue at midnight on March 9 in America/Los\\_Angeles (which equals a UTC timestamp of 2021-03-10T08:00:00Z).
    #[serde(rename = "due_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<Option<String>>,
    #[serde(rename = "fixed_amount_requested_money", skip_serializing_if = "Option::is_none")]
    pub fixed_amount_requested_money: Option<Box<models::Money>>,
    /// Specifies the amount for the payment request in percentage:  - When the payment `request_type` is `DEPOSIT`, it is the percentage of the order's total amount. - When the payment `request_type` is `INSTALLMENT`, it is the percentage of the order's total less  the deposit, if requested. The sum of the `percentage_requested` in all installment  payment requests must be equal to 100.  You cannot specify this when the payment `request_type` is `BALANCE` or when the  payment request specifies the `fixed_amount_requested_money` field.
    #[serde(rename = "percentage_requested", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub percentage_requested: Option<Option<String>>,
    /// If set to true, the Square-hosted invoice page (the `public_url` field of the invoice)  provides a place for the customer to pay a tip.   This field is allowed only on the final payment request   and the payment `request_type` must be `BALANCE` or `INSTALLMENT`.
    #[serde(rename = "tipping_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tipping_enabled: Option<Option<bool>>,
    #[serde(rename = "automatic_payment_source", skip_serializing_if = "Option::is_none")]
    pub automatic_payment_source: Option<models::InvoiceAutomaticPaymentSource>,
    /// The ID of the credit or debit card on file to charge for the payment request. To get the cards on file for a customer, call [ListCards](api-endpoint:Cards-ListCards) and include the `customer_id` of the invoice recipient.
    #[serde(rename = "card_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<Option<String>>,
    /// A list of one or more reminders to send for the payment request.
    #[serde(rename = "reminders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reminders: Option<Option<Vec<models::InvoicePaymentReminder>>>,
    #[serde(rename = "computed_amount_money", skip_serializing_if = "Option::is_none")]
    pub computed_amount_money: Option<Box<models::Money>>,
    #[serde(rename = "total_completed_amount_money", skip_serializing_if = "Option::is_none")]
    pub total_completed_amount_money: Option<Box<models::Money>>,
    #[serde(rename = "rounding_adjustment_included_money", skip_serializing_if = "Option::is_none")]
    pub rounding_adjustment_included_money: Option<Box<models::Money>>,
}

impl InvoicePaymentRequest {
    /// Represents a payment request for an [invoice](entity:Invoice). Invoices can specify a maximum of 13 payment requests, with up to 12 `INSTALLMENT` request types. For more information,  see [Configuring payment requests](https://developer.squareup.com/docs/invoices-api/create-publish-invoices#payment-requests).  Adding `INSTALLMENT` payment requests to an invoice requires an  [Invoices Plus subscription](https://developer.squareup.com/docs/invoices-api/overview#invoices-plus-subscription).
    pub fn new() -> InvoicePaymentRequest {
        InvoicePaymentRequest {
            uid: None,
            request_method: None,
            request_type: None,
            due_date: None,
            fixed_amount_requested_money: None,
            percentage_requested: None,
            tipping_enabled: None,
            automatic_payment_source: None,
            card_id: None,
            reminders: None,
            computed_amount_money: None,
            total_completed_amount_money: None,
            rounding_adjustment_included_money: None,
        }
    }
}

