/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoiceRequestType : Indicates the type of the payment request. For more information, see  [Configuring payment requests](https://developer.squareup.com/docs/invoices-api/create-publish-invoices#payment-requests).
/// Indicates the type of the payment request. For more information, see  [Configuring payment requests](https://developer.squareup.com/docs/invoices-api/create-publish-invoices#payment-requests).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceRequestType {
    #[serde(rename = "BALANCE")]
    Balance,
    #[serde(rename = "DEPOSIT")]
    Deposit,
    #[serde(rename = "INSTALLMENT")]
    Installment,

}

impl std::fmt::Display for InvoiceRequestType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Balance => write!(f, "BALANCE"),
            Self::Deposit => write!(f, "DEPOSIT"),
            Self::Installment => write!(f, "INSTALLMENT"),
        }
    }
}

impl Default for InvoiceRequestType {
    fn default() -> InvoiceRequestType {
        Self::Balance
    }
}

