/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLocationBookingProfilesResponse {
    /// The list of a seller's location booking profiles.
    #[serde(rename = "location_booking_profiles", skip_serializing_if = "Option::is_none")]
    pub location_booking_profiles: Option<Vec<models::LocationBookingProfile>>,
    /// The pagination cursor to be used in the subsequent request to get the next page of the results. Stop retrieving the next page of the results when the cursor is not set.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl ListLocationBookingProfilesResponse {
    pub fn new() -> ListLocationBookingProfilesResponse {
        ListLocationBookingProfilesResponse {
            location_booking_profiles: None,
            cursor: None,
            errors: None,
        }
    }
}

