/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ListChannelsRequestConstants {
    #[serde(rename = "MAX_PAGE_SIZE")]
    MaxPageSize,

}

impl std::fmt::Display for ListChannelsRequestConstants {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MaxPageSize => write!(f, "MAX_PAGE_SIZE"),
        }
    }
}

impl Default for ListChannelsRequestConstants {
    fn default() -> ListChannelsRequestConstants {
        Self::MaxPageSize
    }
}

