/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListLocationsResponse : Defines the fields that are included in the response body of a request to the [ListLocations](api-endpoint:Locations-ListLocations) endpoint.  Either `errors` or `locations` is present in a given response (never both).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLocationsResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The business locations.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<models::Location>>,
}

impl ListLocationsResponse {
    /// Defines the fields that are included in the response body of a request to the [ListLocations](api-endpoint:Locations-ListLocations) endpoint.  Either `errors` or `locations` is present in a given response (never both).
    pub fn new() -> ListLocationsResponse {
        ListLocationsResponse {
            errors: None,
            locations: None,
        }
    }
}

