/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListSitesResponse : Represents a `ListSites` response. The response can include either `sites` or `errors`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSitesResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The sites that belong to the seller.
    #[serde(rename = "sites", skip_serializing_if = "Option::is_none")]
    pub sites: Option<Vec<models::Site>>,
}

impl ListSitesResponse {
    /// Represents a `ListSites` response. The response can include either `sites` or `errors`.
    pub fn new() -> ListSitesResponse {
        ListSitesResponse {
            errors: None,
            sites: None,
        }
    }
}

