/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationSettingsUpdatedEventObject {
    #[serde(rename = "location_settings", skip_serializing_if = "Option::is_none")]
    pub location_settings: Option<Box<models::CheckoutLocationSettings>>,
}

impl LocationSettingsUpdatedEventObject {
    pub fn new() -> LocationSettingsUpdatedEventObject {
        LocationSettingsUpdatedEventObject {
            location_settings: None,
        }
    }
}

