/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LocationCustomAttributeDefinitionVisibleUpdatedEvent : Published when a location [custom attribute definition](entity:CustomAttributeDefinition)  that is visible to the subscribing application is updated. A custom attribute definition can only be updated by the application that created it. A notification is sent when your application updates a custom attribute  definition or when another application updates a custom attribute definition whose `visibility` is  `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationCustomAttributeDefinitionVisibleUpdatedEvent {
    /// The ID of the seller associated with the event that triggered the event notification.
    #[serde(rename = "merchant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<Option<String>>,
    /// The type of this event. The value is `\"location.custom_attribute_definition.visible.updated\"`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// A unique ID for the event notification.
    #[serde(rename = "event_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<Option<String>>,
    /// The timestamp that indicates when the event notification was created, in RFC 3339 format.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::CustomAttributeDefinitionEventData>>,
}

impl LocationCustomAttributeDefinitionVisibleUpdatedEvent {
    /// Published when a location [custom attribute definition](entity:CustomAttributeDefinition)  that is visible to the subscribing application is updated. A custom attribute definition can only be updated by the application that created it. A notification is sent when your application updates a custom attribute  definition or when another application updates a custom attribute definition whose `visibility` is  `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.
    pub fn new() -> LocationCustomAttributeDefinitionVisibleUpdatedEvent {
        LocationCustomAttributeDefinitionVisibleUpdatedEvent {
            merchant_id: None,
            r#type: None,
            event_id: None,
            created_at: None,
            data: None,
        }
    }
}

