/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LocationCustomAttributeOwnedUpdatedEvent : Published when a location [custom attribute](entity:CustomAttribute) owned by the subscribing application is created or updated. Custom attributes are owned by the application that created the corresponding [custom attribute definition](entity:CustomAttributeDefinition). Custom attributes whose `visibility` is `VISIBILITY_READ_WRITE_VALUES` can be created or updated by any application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationCustomAttributeOwnedUpdatedEvent {
    /// The ID of the seller associated with the event that triggered the event notification.
    #[serde(rename = "merchant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<Option<String>>,
    /// The type of this event. The value is `\"location.custom_attribute.owned.updated\"`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// A unique ID for the event notification.
    #[serde(rename = "event_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<Option<String>>,
    /// The timestamp that indicates when the event notification was created, in RFC 3339 format.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::CustomAttributeEventData>>,
}

impl LocationCustomAttributeOwnedUpdatedEvent {
    /// Published when a location [custom attribute](entity:CustomAttribute) owned by the subscribing application is created or updated. Custom attributes are owned by the application that created the corresponding [custom attribute definition](entity:CustomAttributeDefinition). Custom attributes whose `visibility` is `VISIBILITY_READ_WRITE_VALUES` can be created or updated by any application.
    pub fn new() -> LocationCustomAttributeOwnedUpdatedEvent {
        LocationCustomAttributeOwnedUpdatedEvent {
            merchant_id: None,
            r#type: None,
            event_id: None,
            created_at: None,
            data: None,
        }
    }
}

