/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyProgramStatus : Indicates whether the program is currently active.
/// Indicates whether the program is currently active.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoyaltyProgramStatus {
    #[serde(rename = "INACTIVE")]
    Inactive,
    #[serde(rename = "ACTIVE")]
    Active,

}

impl std::fmt::Display for LoyaltyProgramStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Inactive => write!(f, "INACTIVE"),
            Self::Active => write!(f, "ACTIVE"),
        }
    }
}

impl Default for LoyaltyProgramStatus {
    fn default() -> LoyaltyProgramStatus {
        Self::Inactive
    }
}

