/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyProgramExpirationPolicy : Describes when the loyalty program expires.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyProgramExpirationPolicy {
    /// The number of months before points expire, in `P[n]M` RFC 3339 duration format. For example, a value of `P12M` represents a duration of 12 months.  Points are valid through the last day of the month in which they are scheduled to expire. For example, with a  `P12M` duration, points earned on July 6, 2020 expire on August 1, 2021.
    #[serde(rename = "expiration_duration")]
    pub expiration_duration: String,
}

impl LoyaltyProgramExpirationPolicy {
    /// Describes when the loyalty program expires.
    pub fn new(expiration_duration: String) -> LoyaltyProgramExpirationPolicy {
        LoyaltyProgramExpirationPolicy {
            expiration_duration,
        }
    }
}

