/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventFilter : The filtering criteria. If the request specifies multiple filters,  the endpoint uses a logical AND to evaluate them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventFilter {
    #[serde(rename = "loyalty_account_filter", skip_serializing_if = "Option::is_none")]
    pub loyalty_account_filter: Option<Box<models::LoyaltyEventLoyaltyAccountFilter>>,
    #[serde(rename = "type_filter", skip_serializing_if = "Option::is_none")]
    pub type_filter: Option<Box<models::LoyaltyEventTypeFilter>>,
    #[serde(rename = "date_time_filter", skip_serializing_if = "Option::is_none")]
    pub date_time_filter: Option<Box<models::LoyaltyEventDateTimeFilter>>,
    #[serde(rename = "location_filter", skip_serializing_if = "Option::is_none")]
    pub location_filter: Option<Box<models::LoyaltyEventLocationFilter>>,
    #[serde(rename = "order_filter", skip_serializing_if = "Option::is_none")]
    pub order_filter: Option<Box<models::LoyaltyEventOrderFilter>>,
}

impl LoyaltyEventFilter {
    /// The filtering criteria. If the request specifies multiple filters,  the endpoint uses a logical AND to evaluate them.
    pub fn new() -> LoyaltyEventFilter {
        LoyaltyEventFilter {
            loyalty_account_filter: None,
            type_filter: None,
            date_time_filter: None,
            location_filter: None,
            order_filter: None,
        }
    }
}

