/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyProgramAccrualRuleTaxMode : Indicates how taxes should be treated when calculating the purchase amount used for loyalty points accrual.  This setting applies only to `SPEND` accrual rules or `VISIT` accrual rules that have a minimum spend requirement.
/// Indicates how taxes should be treated when calculating the purchase amount used for loyalty points accrual.  This setting applies only to `SPEND` accrual rules or `VISIT` accrual rules that have a minimum spend requirement.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoyaltyProgramAccrualRuleTaxMode {
    #[serde(rename = "BEFORE_TAX")]
    BeforeTax,
    #[serde(rename = "AFTER_TAX")]
    AfterTax,

}

impl std::fmt::Display for LoyaltyProgramAccrualRuleTaxMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BeforeTax => write!(f, "BEFORE_TAX"),
            Self::AfterTax => write!(f, "AFTER_TAX"),
        }
    }
}

impl Default for LoyaltyProgramAccrualRuleTaxMode {
    fn default() -> LoyaltyProgramAccrualRuleTaxMode {
        Self::BeforeTax
    }
}

