/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventAccumulatePoints : Provides metadata when the event `type` is `ACCUMULATE_POINTS`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventAccumulatePoints {
    /// The ID of the [loyalty program](entity:LoyaltyProgram).
    #[serde(rename = "loyalty_program_id", skip_serializing_if = "Option::is_none")]
    pub loyalty_program_id: Option<String>,
    /// The number of points accumulated by the event.
    #[serde(rename = "points", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub points: Option<Option<i32>>,
    /// The ID of the [order](entity:Order) for which the buyer accumulated the points. This field is returned only if the Orders API is used to process orders.
    #[serde(rename = "order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Option<String>>,
}

impl LoyaltyEventAccumulatePoints {
    /// Provides metadata when the event `type` is `ACCUMULATE_POINTS`.
    pub fn new() -> LoyaltyEventAccumulatePoints {
        LoyaltyEventAccumulatePoints {
            loyalty_program_id: None,
            points: None,
            order_id: None,
        }
    }
}

