/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventTypeFilter : Filter events by event type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventTypeFilter {
    /// The loyalty event types used to filter the result. If multiple values are specified, the endpoint uses a  logical OR to combine them. See [LoyaltyEventType](#type-loyaltyeventtype) for possible values
    #[serde(rename = "types")]
    pub types: Vec<models::LoyaltyEventType>,
}

impl LoyaltyEventTypeFilter {
    /// Filter events by event type.
    pub fn new(types: Vec<models::LoyaltyEventType>) -> LoyaltyEventTypeFilter {
        LoyaltyEventTypeFilter {
            types,
        }
    }
}

