/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventDateTimeFilter : Filter events by date time range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventDateTimeFilter {
    #[serde(rename = "created_at")]
    pub created_at: Box<models::TimeRange>,
}

impl LoyaltyEventDateTimeFilter {
    /// Filter events by date time range.
    pub fn new(created_at: models::TimeRange) -> LoyaltyEventDateTimeFilter {
        LoyaltyEventDateTimeFilter {
            created_at: Box::new(created_at),
        }
    }
}

