/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventRedeemReward : Provides metadata when the event `type` is `REDEEM_REWARD`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventRedeemReward {
    /// The ID of the [loyalty program](entity:LoyaltyProgram).
    #[serde(rename = "loyalty_program_id")]
    pub loyalty_program_id: String,
    /// The ID of the redeemed [loyalty reward](entity:LoyaltyReward). This field is returned only if the event source is `LOYALTY_API`.
    #[serde(rename = "reward_id", skip_serializing_if = "Option::is_none")]
    pub reward_id: Option<String>,
    /// The ID of the [order](entity:Order) that redeemed the reward. This field is returned only if the Orders API is used to process orders.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
}

impl LoyaltyEventRedeemReward {
    /// Provides metadata when the event `type` is `REDEEM_REWARD`.
    pub fn new(loyalty_program_id: String) -> LoyaltyEventRedeemReward {
        LoyaltyEventRedeemReward {
            loyalty_program_id,
            reward_id: None,
            order_id: None,
        }
    }
}

