/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyAccountUpdatedEventObject {
    #[serde(rename = "loyalty_account", skip_serializing_if = "Option::is_none")]
    pub loyalty_account: Option<Box<models::LoyaltyAccount>>,
}

impl LoyaltyAccountUpdatedEventObject {
    pub fn new() -> LoyaltyAccountUpdatedEventObject {
        LoyaltyAccountUpdatedEventObject {
            loyalty_account: None,
        }
    }
}

