/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyEventAdjustPoints : Provides metadata when the event `type` is `ADJUST_POINTS`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyEventAdjustPoints {
    /// The Square-assigned ID of the [loyalty program](entity:LoyaltyProgram).
    #[serde(rename = "loyalty_program_id", skip_serializing_if = "Option::is_none")]
    pub loyalty_program_id: Option<String>,
    /// The number of points added or removed.
    #[serde(rename = "points")]
    pub points: i32,
    /// The reason for the adjustment of points.
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl LoyaltyEventAdjustPoints {
    /// Provides metadata when the event `type` is `ADJUST_POINTS`.
    pub fn new(points: i32) -> LoyaltyEventAdjustPoints {
        LoyaltyEventAdjustPoints {
            loyalty_program_id: None,
            points,
            reason: None,
        }
    }
}

