/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoyaltyProgramAccrualRuleCategoryData : Represents additional data for rules with the `CATEGORY` accrual type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltyProgramAccrualRuleCategoryData {
    /// The ID of the `CATEGORY` [catalog object](entity:CatalogObject) that buyers can purchase to earn points.
    #[serde(rename = "category_id")]
    pub category_id: String,
}

impl LoyaltyProgramAccrualRuleCategoryData {
    /// Represents additional data for rules with the `CATEGORY` accrual type.
    pub fn new(category_id: String) -> LoyaltyProgramAccrualRuleCategoryData {
        LoyaltyProgramAccrualRuleCategoryData {
            category_id,
        }
    }
}

