/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeasurementUnitCustom : The information needed to define a custom unit, provided by the seller.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementUnitCustom {
    /// The name of the custom unit, for example \"bushel\".
    #[serde(rename = "name")]
    pub name: String,
    /// The abbreviation of the custom unit, such as \"bsh\" (bushel). This appears in the cart for the Point of Sale app, and in reports.
    #[serde(rename = "abbreviation")]
    pub abbreviation: String,
}

impl MeasurementUnitCustom {
    /// The information needed to define a custom unit, provided by the seller.
    pub fn new(name: String, abbreviation: String) -> MeasurementUnitCustom {
        MeasurementUnitCustom {
            name,
            abbreviation,
        }
    }
}

