/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeasurementUnit : Represents a unit of measurement to use with a quantity, such as ounces or inches. Exactly one of the following fields are required: `custom_unit`, `area_unit`, `length_unit`, `volume_unit`, and `weight_unit`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementUnit {
    #[serde(rename = "custom_unit", skip_serializing_if = "Option::is_none")]
    pub custom_unit: Option<Box<models::MeasurementUnitCustom>>,
    #[serde(rename = "area_unit", skip_serializing_if = "Option::is_none")]
    pub area_unit: Option<models::MeasurementUnitArea>,
    #[serde(rename = "length_unit", skip_serializing_if = "Option::is_none")]
    pub length_unit: Option<models::MeasurementUnitLength>,
    #[serde(rename = "volume_unit", skip_serializing_if = "Option::is_none")]
    pub volume_unit: Option<models::MeasurementUnitVolume>,
    #[serde(rename = "weight_unit", skip_serializing_if = "Option::is_none")]
    pub weight_unit: Option<models::MeasurementUnitWeight>,
    #[serde(rename = "generic_unit", skip_serializing_if = "Option::is_none")]
    pub generic_unit: Option<models::MeasurementUnitGeneric>,
    #[serde(rename = "time_unit", skip_serializing_if = "Option::is_none")]
    pub time_unit: Option<models::MeasurementUnitTime>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::MeasurementUnitUnitType>,
}

impl MeasurementUnit {
    /// Represents a unit of measurement to use with a quantity, such as ounces or inches. Exactly one of the following fields are required: `custom_unit`, `area_unit`, `length_unit`, `volume_unit`, and `weight_unit`.
    pub fn new() -> MeasurementUnit {
        MeasurementUnit {
            custom_unit: None,
            area_unit: None,
            length_unit: None,
            volume_unit: None,
            weight_unit: None,
            generic_unit: None,
            time_unit: None,
            r#type: None,
        }
    }
}

