/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeasurementUnitTime : Unit of time used to measure a quantity (a duration).
/// Unit of time used to measure a quantity (a duration).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasurementUnitTime {
    #[serde(rename = "GENERIC_MILLISECOND")]
    GenericMillisecond,
    #[serde(rename = "GENERIC_SECOND")]
    GenericSecond,
    #[serde(rename = "GENERIC_MINUTE")]
    GenericMinute,
    #[serde(rename = "GENERIC_HOUR")]
    GenericHour,
    #[serde(rename = "GENERIC_DAY")]
    GenericDay,

}

impl std::fmt::Display for MeasurementUnitTime {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GenericMillisecond => write!(f, "GENERIC_MILLISECOND"),
            Self::GenericSecond => write!(f, "GENERIC_SECOND"),
            Self::GenericMinute => write!(f, "GENERIC_MINUTE"),
            Self::GenericHour => write!(f, "GENERIC_HOUR"),
            Self::GenericDay => write!(f, "GENERIC_DAY"),
        }
    }
}

impl Default for MeasurementUnitTime {
    fn default() -> MeasurementUnitTime {
        Self::GenericMillisecond
    }
}

