/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeasurementUnitLength : The unit of length used to measure a quantity.
/// The unit of length used to measure a quantity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasurementUnitLength {
    #[serde(rename = "IMPERIAL_INCH")]
    ImperialInch,
    #[serde(rename = "IMPERIAL_FOOT")]
    ImperialFoot,
    #[serde(rename = "IMPERIAL_YARD")]
    ImperialYard,
    #[serde(rename = "IMPERIAL_MILE")]
    ImperialMile,
    #[serde(rename = "METRIC_MILLIMETER")]
    MetricMillimeter,
    #[serde(rename = "METRIC_CENTIMETER")]
    MetricCentimeter,
    #[serde(rename = "METRIC_METER")]
    MetricMeter,
    #[serde(rename = "METRIC_KILOMETER")]
    MetricKilometer,

}

impl std::fmt::Display for MeasurementUnitLength {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ImperialInch => write!(f, "IMPERIAL_INCH"),
            Self::ImperialFoot => write!(f, "IMPERIAL_FOOT"),
            Self::ImperialYard => write!(f, "IMPERIAL_YARD"),
            Self::ImperialMile => write!(f, "IMPERIAL_MILE"),
            Self::MetricMillimeter => write!(f, "METRIC_MILLIMETER"),
            Self::MetricCentimeter => write!(f, "METRIC_CENTIMETER"),
            Self::MetricMeter => write!(f, "METRIC_METER"),
            Self::MetricKilometer => write!(f, "METRIC_KILOMETER"),
        }
    }
}

impl Default for MeasurementUnitLength {
    fn default() -> MeasurementUnitLength {
        Self::ImperialInch
    }
}

