/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthAuthorizationRevokedEventRevocationObject {
    /// Timestamp of when the revocation event occurred, in RFC 3339 format.
    #[serde(rename = "revoked_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<Option<String>>,
    #[serde(rename = "revoker_type", skip_serializing_if = "Option::is_none")]
    pub revoker_type: Option<models::OauthAuthorizationRevokedEventRevokerType>,
}

impl OauthAuthorizationRevokedEventRevocationObject {
    pub fn new() -> OauthAuthorizationRevokedEventRevocationObject {
        OauthAuthorizationRevokedEventRevocationObject {
            revoked_at: None,
            revoker_type: None,
        }
    }
}

