/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ObtainTokenRequest : Represents an [ObtainToken](api-endpoint:OAuth-ObtainToken) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObtainTokenRequest {
    /// The Square-issued ID of your application, which is available as the **Application ID** on the **OAuth** page in the [Developer Console](https://developer.squareup.com/apps).  Required for the code flow and PKCE flow for any grant type.
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// The secret key for your application, which is available as the **Application secret** on the **OAuth** page in the [Developer Console](https://developer.squareup.com/apps).  Required for the code flow for any grant type. Don't confuse your client secret with your personal access token.
    #[serde(rename = "client_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<Option<String>>,
    /// The authorization code to exchange for an OAuth access token. This is the `code` value that Square sent to your redirect URL in the authorization response.  Required for the code flow and PKCE flow if `grant_type` is `authorization_code`.
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    /// The redirect URL for your application, which you registered as the **Redirect URL** on the **OAuth** page in the [Developer Console](https://developer.squareup.com/apps).  Required for the code flow and PKCE flow if `grant_type` is `authorization_code` and you provided the `redirect_uri` parameter in your authorization URL.
    #[serde(rename = "redirect_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub redirect_uri: Option<Option<String>>,
    /// The method used to obtain an OAuth access token. The request must include the credential that corresponds to the specified grant type. Valid values are: - `authorization_code` - Requires the `code` field. - `refresh_token` - Requires the `refresh_token` field. - `migration_token` - LEGACY for access tokens obtained using a Square API version prior to 2019-03-13. Requires the `migration_token` field.
    #[serde(rename = "grant_type")]
    pub grant_type: String,
    /// A valid refresh token used to generate a new OAuth access token. This is a refresh token that was returned in a previous `ObtainToken` response.  Required for the code flow and PKCE flow if `grant_type` is `refresh_token`.
    #[serde(rename = "refresh_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<Option<String>>,
    /// __LEGACY__ A valid access token (obtained using a Square API version prior to 2019-03-13) used to generate a new OAuth access token.  Required if `grant_type` is `migration_token`. For more information, see [Migrate to Using Refresh Tokens](https://developer.squareup.com/docs/oauth-api/migrate-to-refresh-tokens).
    #[serde(rename = "migration_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub migration_token: Option<Option<String>>,
    /// The list of permissions that are explicitly requested for the access token. For example, [\"MERCHANT_PROFILE_READ\",\"PAYMENTS_READ\",\"BANK_ACCOUNTS_READ\"].  The returned access token is limited to the permissions that are the intersection of these requested permissions and those authorized by the provided `refresh_token`.  Optional for the code flow and PKCE flow if `grant_type` is `refresh_token`.
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<Vec<String>>>,
    /// Indicates whether the returned access token should expire in 24 hours.  Optional for the code flow and PKCE flow for any grant type. The default value is `false`.
    #[serde(rename = "short_lived", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub short_lived: Option<Option<bool>>,
    /// The secret your application generated for the authorization request used to obtain the authorization code. This is the source of the `code_challenge` hash you provided in your authorization URL.  Required for the PKCE flow if `grant_type` is `authorization_code`.
    #[serde(rename = "code_verifier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code_verifier: Option<Option<String>>,
}

impl ObtainTokenRequest {
    /// Represents an [ObtainToken](api-endpoint:OAuth-ObtainToken) request.
    pub fn new(client_id: String, grant_type: String) -> ObtainTokenRequest {
        ObtainTokenRequest {
            client_id,
            client_secret: None,
            code: None,
            redirect_uri: None,
            grant_type,
            refresh_token: None,
            migration_token: None,
            scopes: None,
            short_lived: None,
            code_verifier: None,
        }
    }
}

