/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderLineItemPricingBlocklistsBlockedServiceCharge : A service charge to block from applying to a line item. The service charge must be identified by either `service_charge_uid` or `service_charge_catalog_object_id`, but not both.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderLineItemPricingBlocklistsBlockedServiceCharge {
    /// A unique ID of the `BlockedServiceCharge` within the order.
    #[serde(rename = "uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uid: Option<Option<String>>,
    /// The `uid` of the service charge that should be blocked. Use this field to block ad hoc service charges. For catalog service charges, use the  `service_charge_catalog_object_id` field.
    #[serde(rename = "service_charge_uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_charge_uid: Option<Option<String>>,
    /// The `catalog_object_id` of the service charge that should be blocked. Use this field to block catalog service charges. For ad hoc service charges, use the `service_charge_uid` field.
    #[serde(rename = "service_charge_catalog_object_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_charge_catalog_object_id: Option<Option<String>>,
}

impl OrderLineItemPricingBlocklistsBlockedServiceCharge {
    /// A service charge to block from applying to a line item. The service charge must be identified by either `service_charge_uid` or `service_charge_catalog_object_id`, but not both.
    pub fn new() -> OrderLineItemPricingBlocklistsBlockedServiceCharge {
        OrderLineItemPricingBlocklistsBlockedServiceCharge {
            uid: None,
            service_charge_uid: None,
            service_charge_catalog_object_id: None,
        }
    }
}

