/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderLineItemTaxType : Indicates how the tax is applied to the associated line item or order.
/// Indicates how the tax is applied to the associated line item or order.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderLineItemTaxType {
    #[serde(rename = "UNKNOWN_TAX")]
    UnknownTax,
    #[serde(rename = "ADDITIVE")]
    Additive,
    #[serde(rename = "INCLUSIVE")]
    Inclusive,

}

impl std::fmt::Display for OrderLineItemTaxType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UnknownTax => write!(f, "UNKNOWN_TAX"),
            Self::Additive => write!(f, "ADDITIVE"),
            Self::Inclusive => write!(f, "INCLUSIVE"),
        }
    }
}

impl Default for OrderLineItemTaxType {
    fn default() -> OrderLineItemTaxType {
        Self::UnknownTax
    }
}

