/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderReturnTip : A tip being returned.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderReturnTip {
    /// A unique ID that identifies the tip only within this order.
    #[serde(rename = "uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uid: Option<Option<String>>,
    #[serde(rename = "applied_money", skip_serializing_if = "Option::is_none")]
    pub applied_money: Option<Box<models::Money>>,
    /// The tender `uid` from the order that contains the original application of this tip.
    #[serde(rename = "source_tender_uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_tender_uid: Option<Option<String>>,
    /// The tender `id` from the order that contains the original application of this tip.
    #[serde(rename = "source_tender_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_tender_id: Option<Option<String>>,
}

impl OrderReturnTip {
    /// A tip being returned.
    pub fn new() -> OrderReturnTip {
        OrderReturnTip {
            uid: None,
            applied_money: None,
            source_tender_uid: None,
            source_tender_id: None,
        }
    }
}

