/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderUpdatedObject {
    #[serde(rename = "order_updated", skip_serializing_if = "Option::is_none")]
    pub order_updated: Option<Box<models::OrderUpdated>>,
}

impl OrderUpdatedObject {
    pub fn new() -> OrderUpdatedObject {
        OrderUpdatedObject {
            order_updated: None,
        }
    }
}

