/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderPricingOptions : Pricing options for an order. The options affect how the order's price is calculated. They can be used, for example, to apply automatic price adjustments that are based on preconfigured [pricing rules](entity:CatalogPricingRule).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderPricingOptions {
    /// The option to determine whether pricing rule-based discounts are automatically applied to an order.
    #[serde(rename = "auto_apply_discounts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_apply_discounts: Option<Option<bool>>,
    /// The option to determine whether rule-based taxes are automatically applied to an order when the criteria of the corresponding rules are met.
    #[serde(rename = "auto_apply_taxes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_apply_taxes: Option<Option<bool>>,
}

impl OrderPricingOptions {
    /// Pricing options for an order. The options affect how the order's price is calculated. They can be used, for example, to apply automatic price adjustments that are based on preconfigured [pricing rules](entity:CatalogPricingRule).
    pub fn new() -> OrderPricingOptions {
        OrderPricingOptions {
            auto_apply_discounts: None,
            auto_apply_taxes: None,
        }
    }
}

