/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderUpdated {
    /// The order's unique ID.
    #[serde(rename = "order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Option<String>>,
    /// The version number, which is incremented each time an update is committed to the order. Orders that were not created through the API do not include a version number and therefore cannot be updated.  [Read more about working with versions.](https://developer.squareup.com/docs/orders-api/manage-orders/update-orders)
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// The ID of the seller location that this order is associated with.
    #[serde(rename = "location_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Option<String>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::OrderState>,
    /// The timestamp for when the order was created, in RFC 3339 format.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The timestamp for when the order was last updated, in RFC 3339 format.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl OrderUpdated {
    pub fn new() -> OrderUpdated {
        OrderUpdated {
            order_id: None,
            version: None,
            location_id: None,
            state: None,
            created_at: None,
            updated_at: None,
        }
    }
}

