/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderLineItemModifier : A [CatalogModifier](entity:CatalogModifier).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderLineItemModifier {
    /// A unique ID that identifies the modifier only within this order.
    #[serde(rename = "uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uid: Option<Option<String>>,
    /// The catalog object ID referencing [CatalogModifier](entity:CatalogModifier).
    #[serde(rename = "catalog_object_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub catalog_object_id: Option<Option<String>>,
    /// The version of the catalog object that this modifier references.
    #[serde(rename = "catalog_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub catalog_version: Option<Option<i64>>,
    /// The name of the item modifier.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The quantity of the line item modifier. The modifier quantity can be 0 or more. For example, suppose a restaurant offers a cheeseburger on the menu. When a buyer orders this item, the restaurant records the purchase by creating an `Order` object with a line item for a burger. The line item includes a line item modifier: the name is cheese and the quantity is 1. The buyer has the option to order extra cheese (or no cheese). If the buyer chooses the extra cheese option, the modifier quantity increases to 2. If the buyer does not want any cheese, the modifier quantity is set to 0.
    #[serde(rename = "quantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Option<String>>,
    #[serde(rename = "base_price_money", skip_serializing_if = "Option::is_none")]
    pub base_price_money: Option<Box<models::Money>>,
    #[serde(rename = "total_price_money", skip_serializing_if = "Option::is_none")]
    pub total_price_money: Option<Box<models::Money>>,
    /// Application-defined data attached to this order. Metadata fields are intended to store descriptive references or associations with an entity in another system or store brief information about the object. Square does not process this field; it only stores and returns it in relevant API calls. Do not use metadata to store any sensitive information (such as personally identifiable information or card details).  Keys written by applications must be 60 characters or less and must be in the character set `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed with a namespace, separated from the key with a ':' character.  Values have a maximum length of 255 characters.  An application can have up to 10 entries per metadata field.  Entries written by applications are private and can only be read or modified by the same application.  For more information, see  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, String>>>,
}

impl OrderLineItemModifier {
    /// A [CatalogModifier](entity:CatalogModifier).
    pub fn new() -> OrderLineItemModifier {
        OrderLineItemModifier {
            uid: None,
            catalog_object_id: None,
            catalog_version: None,
            name: None,
            quantity: None,
            base_price_money: None,
            total_price_money: None,
            metadata: None,
        }
    }
}

