/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentBalanceActivityReserveReleaseDetail {
    /// The ID of the payment associated with this activity.
    #[serde(rename = "payment_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Option<String>>,
}

impl PaymentBalanceActivityReserveReleaseDetail {
    pub fn new() -> PaymentBalanceActivityReserveReleaseDetail {
        PaymentBalanceActivityReserveReleaseDetail {
            payment_id: None,
        }
    }
}

