/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentBalanceActivityAppFeeRefundDetail {
    /// The ID of the payment associated with this activity.
    #[serde(rename = "payment_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Option<String>>,
    /// The ID of the refund associated with this activity.
    #[serde(rename = "refund_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refund_id: Option<Option<String>>,
    /// The ID of the location of the merchant associated with the payment refund activity
    #[serde(rename = "location_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Option<String>>,
}

impl PaymentBalanceActivityAppFeeRefundDetail {
    pub fn new() -> PaymentBalanceActivityAppFeeRefundDetail {
        PaymentBalanceActivityAppFeeRefundDetail {
            payment_id: None,
            refund_id: None,
            location_id: None,
        }
    }
}

