/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentOptions {
    /// Indicates whether the `Payment` objects created from this `TerminalCheckout` are automatically `COMPLETED` or left in an `APPROVED` state for later modification.  Default: true
    #[serde(rename = "autocomplete", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub autocomplete: Option<Option<bool>>,
    /// The duration of time after the payment's creation when Square automatically resolves the payment. This automatic resolution applies only to payments that do not reach a terminal state (`COMPLETED` or `CANCELED`) before the `delay_duration` time period.  This parameter should be specified as a time duration, in RFC 3339 format, with a minimum value of 1 minute and a maximum value of 36 hours. This feature is only supported for card payments, and all payments will be considered card-present.  This parameter can only be set for a delayed capture payment (`autocomplete=false`). For more information, see [Delayed Capture](https://developer.squareup.com/docs/payments-api/take-payments/card-payments/delayed-capture#time-threshold).  Default: \"PT36H\" (36 hours) from the creation time
    #[serde(rename = "delay_duration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delay_duration: Option<Option<String>>,
    /// If set to `true` and charging a Square Gift Card, a payment might be returned with `amount_money` equal to less than what was requested. For example, a request for $20 when charging a Square Gift Card with a balance of $5 results in an APPROVED payment of $5. You might choose to prompt the buyer for an additional payment to cover the remainder or cancel the Gift Card payment.  This parameter can only be set for a delayed capture payment (`autocomplete=false`).  For more information, see [Take Partial Payments](https://developer.squareup.com/docs/payments-api/take-payments/card-payments/partial-payments-with-gift-cards).  Default: false
    #[serde(rename = "accept_partial_authorization", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accept_partial_authorization: Option<Option<bool>>,
    #[serde(rename = "delay_action", skip_serializing_if = "Option::is_none")]
    pub delay_action: Option<models::PaymentOptionsDelayAction>,
}

impl PaymentOptions {
    pub fn new() -> PaymentOptions {
        PaymentOptions {
            autocomplete: None,
            delay_duration: None,
            accept_partial_authorization: None,
            delay_action: None,
        }
    }
}

