/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayoutType : The type of payout: “BATCH” or “SIMPLE”. BATCH payouts include a list of payout entries that can be considered settled. SIMPLE payouts do not have any payout entries associated with them and will show up as one of the payout entries in a future BATCH payout.
/// The type of payout: “BATCH” or “SIMPLE”. BATCH payouts include a list of payout entries that can be considered settled. SIMPLE payouts do not have any payout entries associated with them and will show up as one of the payout entries in a future BATCH payout.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutType {
    #[serde(rename = "BATCH")]
    Batch,
    #[serde(rename = "SIMPLE")]
    Simple,

}

impl std::fmt::Display for PayoutType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Batch => write!(f, "BATCH"),
            Self::Simple => write!(f, "SIMPLE"),
        }
    }
}

impl Default for PayoutType {
    fn default() -> PayoutType {
        Self::Batch
    }
}

