/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayoutFeeType : Represents the type of payout fee that can incur as part of a payout.
/// Represents the type of payout fee that can incur as part of a payout.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutFeeType {
    #[serde(rename = "TRANSFER_FEE")]
    TransferFee,
    #[serde(rename = "TAX_ON_TRANSFER_FEE")]
    TaxOnTransferFee,

}

impl std::fmt::Display for PayoutFeeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TransferFee => write!(f, "TRANSFER_FEE"),
            Self::TaxOnTransferFee => write!(f, "TAX_ON_TRANSFER_FEE"),
        }
    }
}

impl Default for PayoutFeeType {
    fn default() -> PayoutFeeType {
        Self::TransferFee
    }
}

