/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhaseInput : Represents the arguments used to construct a new phase.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhaseInput {
    /// index of phase in total subscription plan
    #[serde(rename = "ordinal")]
    pub ordinal: i64,
    /// id of order to be used in billing
    #[serde(rename = "order_template_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_template_id: Option<Option<String>>,
}

impl PhaseInput {
    /// Represents the arguments used to construct a new phase.
    pub fn new(ordinal: i64) -> PhaseInput {
        PhaseInput {
            ordinal,
            order_template_id: None,
        }
    }
}

