/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiveTransferOrderResponse : Response for receiving items for a transfer order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiveTransferOrderResponse {
    #[serde(rename = "transfer_order", skip_serializing_if = "Option::is_none")]
    pub transfer_order: Option<Box<models::TransferOrder>>,
    /// Any errors that occurred during the request
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl ReceiveTransferOrderResponse {
    /// Response for receiving items for a transfer order
    pub fn new() -> ReceiveTransferOrderResponse {
        ReceiveTransferOrderResponse {
            transfer_order: None,
            errors: None,
        }
    }
}

