/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegisterDomainResponseStatus : The status of the domain registration.
/// The status of the domain registration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegisterDomainResponseStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "VERIFIED")]
    Verified,

}

impl std::fmt::Display for RegisterDomainResponseStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "PENDING"),
            Self::Verified => write!(f, "VERIFIED"),
        }
    }
}

impl Default for RegisterDomainResponseStatus {
    fn default() -> RegisterDomainResponseStatus {
        Self::Pending
    }
}

