/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResumeSubscriptionResponse : Defines output parameters in a response from the  [ResumeSubscription](api-endpoint:Subscriptions-ResumeSubscription) endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResumeSubscriptionResponse {
    /// Errors encountered during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "subscription", skip_serializing_if = "Option::is_none")]
    pub subscription: Option<Box<models::Subscription>>,
    /// A list of `RESUME` actions created by the request and scheduled for the subscription.
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<models::SubscriptionAction>>,
}

impl ResumeSubscriptionResponse {
    /// Defines output parameters in a response from the  [ResumeSubscription](api-endpoint:Subscriptions-ResumeSubscription) endpoint.
    pub fn new() -> ResumeSubscriptionResponse {
        ResumeSubscriptionResponse {
            errors: None,
            subscription: None,
            actions: None,
        }
    }
}

