/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveLoyaltyRewardResponse : A response that includes the loyalty reward.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveLoyaltyRewardResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Box<models::LoyaltyReward>>,
}

impl RetrieveLoyaltyRewardResponse {
    /// A response that includes the loyalty reward.
    pub fn new() -> RetrieveLoyaltyRewardResponse {
        RetrieveLoyaltyRewardResponse {
            errors: None,
            reward: None,
        }
    }
}

