/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveWageSettingResponse : Represents a response from a retrieve request containing the specified `WageSetting` object or error messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveWageSettingResponse {
    #[serde(rename = "wage_setting", skip_serializing_if = "Option::is_none")]
    pub wage_setting: Option<Box<models::WageSetting>>,
    /// The errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl RetrieveWageSettingResponse {
    /// Represents a response from a retrieve request containing the specified `WageSetting` object or error messages.
    pub fn new() -> RetrieveWageSettingResponse {
        RetrieveWageSettingResponse {
            wage_setting: None,
            errors: None,
        }
    }
}

