/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveVendorResponse : Represents an output from a call to [RetrieveVendor](api-endpoint:Vendors-RetrieveVendor).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveVendorResponse {
    /// Errors encountered when the request fails.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<Box<models::Vendor>>,
}

impl RetrieveVendorResponse {
    /// Represents an output from a call to [RetrieveVendor](api-endpoint:Vendors-RetrieveVendor).
    pub fn new() -> RetrieveVendorResponse {
        RetrieveVendorResponse {
            errors: None,
            vendor: None,
        }
    }
}

