/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveTokenStatusResponse : Defines the fields that are included in the response body of a request to the `RetrieveTokenStatus` endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveTokenStatusResponse {
    /// The list of scopes associated with an access token.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    /// The date and time when the `access_token` expires, in RFC 3339 format. Empty if the token never expires.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// The Square-issued application ID associated with the access token. This is the same application ID used to obtain the token.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The ID of the authorizing merchant's business.
    #[serde(rename = "merchant_id", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<String>,
    ///  Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl RetrieveTokenStatusResponse {
    /// Defines the fields that are included in the response body of a request to the `RetrieveTokenStatus` endpoint.
    pub fn new() -> RetrieveTokenStatusResponse {
        RetrieveTokenStatusResponse {
            scopes: None,
            expires_at: None,
            client_id: None,
            merchant_id: None,
            errors: None,
        }
    }
}

