/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveInventoryAdjustmentResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "adjustment", skip_serializing_if = "Option::is_none")]
    pub adjustment: Option<Box<models::InventoryAdjustment>>,
}

impl RetrieveInventoryAdjustmentResponse {
    pub fn new() -> RetrieveInventoryAdjustmentResponse {
        RetrieveInventoryAdjustmentResponse {
            errors: None,
            adjustment: None,
        }
    }
}

