/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveScheduledShiftResponse : Represents a [RetrieveScheduledShift](api-endpoint:Labor-RetrieveScheduledShift) response. Either `scheduled_shift` or `errors` is present in the response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveScheduledShiftResponse {
    #[serde(rename = "scheduled_shift", skip_serializing_if = "Option::is_none")]
    pub scheduled_shift: Option<Box<models::ScheduledShift>>,
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl RetrieveScheduledShiftResponse {
    /// Represents a [RetrieveScheduledShift](api-endpoint:Labor-RetrieveScheduledShift) response. Either `scheduled_shift` or `errors` is present in the response.
    pub fn new() -> RetrieveScheduledShiftResponse {
        RetrieveScheduledShiftResponse {
            scheduled_shift: None,
            errors: None,
        }
    }
}

