/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveBusinessBookingProfileResponse {
    #[serde(rename = "business_booking_profile", skip_serializing_if = "Option::is_none")]
    pub business_booking_profile: Option<Box<models::BusinessBookingProfile>>,
    /// Errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl RetrieveBusinessBookingProfileResponse {
    pub fn new() -> RetrieveBusinessBookingProfileResponse {
        RetrieveBusinessBookingProfileResponse {
            business_booking_profile: None,
            errors: None,
        }
    }
}

