/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeTokenRequest {
    /// The Square-issued ID for your application, which is available on the **OAuth** page in the [Developer Dashboard](https://developer.squareup.com/apps).
    #[serde(rename = "client_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<Option<String>>,
    /// The access token of the merchant whose token you want to revoke. Do not provide a value for `merchant_id` if you provide this parameter.
    #[serde(rename = "access_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<Option<String>>,
    /// The ID of the merchant whose token you want to revoke. Do not provide a value for `access_token` if you provide this parameter.
    #[serde(rename = "merchant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<Option<String>>,
    /// If `true`, terminate the given single access token, but do not terminate the entire authorization. Default: `false`
    #[serde(rename = "revoke_only_access_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoke_only_access_token: Option<Option<bool>>,
}

impl RevokeTokenRequest {
    pub fn new() -> RevokeTokenRequest {
        RevokeTokenRequest {
            client_id: None,
            access_token: None,
            merchant_id: None,
            revoke_only_access_token: None,
        }
    }
}

