/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduledShiftSort : Defines sort criteria for a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledShiftSort {
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<models::ScheduledShiftSortField>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrder>,
}

impl ScheduledShiftSort {
    /// Defines sort criteria for a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) request.
    pub fn new() -> ScheduledShiftSort {
        ScheduledShiftSort {
            field: None,
            order: None,
        }
    }
}

