/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduledShiftQuery : Represents filter and sort criteria for the `query` field in a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledShiftQuery {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::ScheduledShiftFilter>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::ScheduledShiftSort>>,
}

impl ScheduledShiftQuery {
    /// Represents filter and sort criteria for the `query` field in a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) request.
    pub fn new() -> ScheduledShiftQuery {
        ScheduledShiftQuery {
            filter: None,
            sort: None,
        }
    }
}

