/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchVendorsRequestSortField : The field to sort the returned [Vendor](entity:Vendor) objects by.
/// The field to sort the returned [Vendor](entity:Vendor) objects by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchVendorsRequestSortField {
    #[serde(rename = "NAME")]
    Name,
    #[serde(rename = "CREATED_AT")]
    CreatedAt,

}

impl std::fmt::Display for SearchVendorsRequestSortField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Name => write!(f, "NAME"),
            Self::CreatedAt => write!(f, "CREATED_AT"),
        }
    }
}

impl Default for SearchVendorsRequestSortField {
    fn default() -> SearchVendorsRequestSortField {
        Self::Name
    }
}

