/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchVendorsResponse : Represents an output from a call to [SearchVendors](api-endpoint:Vendors-SearchVendors).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchVendorsResponse {
    /// Errors encountered when the request fails.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The [Vendor](entity:Vendor) objects matching the specified search filter.
    #[serde(rename = "vendors", skip_serializing_if = "Option::is_none")]
    pub vendors: Option<Vec<models::Vendor>>,
    /// The pagination cursor to be used in a subsequent request. If unset, this is the final response.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchVendorsResponse {
    /// Represents an output from a call to [SearchVendors](api-endpoint:Vendors-SearchVendors).
    pub fn new() -> SearchVendorsResponse {
        SearchVendorsResponse {
            errors: None,
            vendors: None,
            cursor: None,
        }
    }
}

