/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchTerminalActionsResponse {
    /// Information on errors encountered during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The requested search result of `TerminalAction`s.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Vec<models::TerminalAction>>,
    /// The pagination cursor to be used in a subsequent request. If empty, this is the final response.  See [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination) for more information.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchTerminalActionsResponse {
    pub fn new() -> SearchTerminalActionsResponse {
        SearchTerminalActionsResponse {
            errors: None,
            action: None,
            cursor: None,
        }
    }
}

