/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchSubscriptionsFilter : Represents a set of query expressions (filters) to narrow the scope of targeted subscriptions returned by  the [SearchSubscriptions](api-endpoint:Subscriptions-SearchSubscriptions) endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSubscriptionsFilter {
    /// A filter to select subscriptions based on the subscribing customer IDs.
    #[serde(rename = "customer_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_ids: Option<Option<Vec<String>>>,
    /// A filter to select subscriptions based on the location.
    #[serde(rename = "location_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_ids: Option<Option<Vec<String>>>,
    /// A filter to select subscriptions based on the source application.
    #[serde(rename = "source_names", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_names: Option<Option<Vec<String>>>,
}

impl SearchSubscriptionsFilter {
    /// Represents a set of query expressions (filters) to narrow the scope of targeted subscriptions returned by  the [SearchSubscriptions](api-endpoint:Subscriptions-SearchSubscriptions) endpoint.
    pub fn new() -> SearchSubscriptionsFilter {
        SearchSubscriptionsFilter {
            customer_ids: None,
            location_ids: None,
            source_names: None,
        }
    }
}

