/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchShiftsRequest : A request for a filtered and sorted set of `Shift` objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchShiftsRequest {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::ShiftQuery>>,
    /// The number of resources in a page (200 by default).
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// An opaque cursor for fetching the next page.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchShiftsRequest {
    /// A request for a filtered and sorted set of `Shift` objects.
    pub fn new() -> SearchShiftsRequest {
        SearchShiftsRequest {
            query: None,
            limit: None,
            cursor: None,
        }
    }
}

