/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchEventsQuery : Contains query criteria for the search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchEventsQuery {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::SearchEventsFilter>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::SearchEventsSort>>,
}

impl SearchEventsQuery {
    /// Contains query criteria for the search.
    pub fn new() -> SearchEventsQuery {
        SearchEventsQuery {
            filter: None,
            sort: None,
        }
    }
}

