/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchEventsSort : Criteria to sort events by.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchEventsSort {
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<models::SearchEventsSortField>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrder>,
}

impl SearchEventsSort {
    /// Criteria to sort events by.
    pub fn new() -> SearchEventsSort {
        SearchEventsSort {
            field: None,
            order: None,
        }
    }
}

