/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchTeamMembersRequest : Represents a search request for a filtered list of `TeamMember` objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchTeamMembersRequest {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::SearchTeamMembersQuery>>,
    /// The maximum number of `TeamMember` objects in a page (100 by default).
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// The opaque cursor for fetching the next page. For more information, see [pagination](https://developer.squareup.com/docs/working-with-apis/pagination).
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchTeamMembersRequest {
    /// Represents a search request for a filtered list of `TeamMember` objects.
    pub fn new() -> SearchTeamMembersRequest {
        SearchTeamMembersRequest {
            query: None,
            limit: None,
            cursor: None,
        }
    }
}

