/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchOrdersStateFilter : Filter by the current order `state`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchOrdersStateFilter {
    /// States to filter for. See [OrderState](#type-orderstate) for possible values
    #[serde(rename = "states")]
    pub states: Vec<models::OrderState>,
}

impl SearchOrdersStateFilter {
    /// Filter by the current order `state`.
    pub fn new(states: Vec<models::OrderState>) -> SearchOrdersStateFilter {
        SearchOrdersStateFilter {
            states,
        }
    }
}

