/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchTransferOrdersResponse : Response for searching transfer orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchTransferOrdersResponse {
    /// List of transfer orders matching the search criteria
    #[serde(rename = "transfer_orders", skip_serializing_if = "Option::is_none")]
    pub transfer_orders: Option<Vec<models::TransferOrder>>,
    /// Pagination cursor for fetching the next page of results
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Any errors that occurred during the request
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl SearchTransferOrdersResponse {
    /// Response for searching transfer orders
    pub fn new() -> SearchTransferOrdersResponse {
        SearchTransferOrdersResponse {
            transfer_orders: None,
            cursor: None,
            errors: None,
        }
    }
}

