/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchVendorsRequestFilter : Defines supported query expressions to search for vendors by.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchVendorsRequestFilter {
    /// The names of the [Vendor](entity:Vendor) objects to retrieve.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<Vec<String>>>,
    /// The statuses of the [Vendor](entity:Vendor) objects to retrieve. See [VendorStatus](#type-vendorstatus) for possible values
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<Vec<models::VendorStatus>>>,
}

impl SearchVendorsRequestFilter {
    /// Defines supported query expressions to search for vendors by.
    pub fn new() -> SearchVendorsRequestFilter {
        SearchVendorsRequestFilter {
            name: None,
            status: None,
        }
    }
}

