/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchLoyaltyAccountsResponse : A response that includes loyalty accounts that satisfy the search criteria.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchLoyaltyAccountsResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The loyalty accounts that met the search criteria,   in order of creation date.
    #[serde(rename = "loyalty_accounts", skip_serializing_if = "Option::is_none")]
    pub loyalty_accounts: Option<Vec<models::LoyaltyAccount>>,
    /// The pagination cursor to use in a subsequent  request. If empty, this is the final response. For more information,  see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchLoyaltyAccountsResponse {
    /// A response that includes loyalty accounts that satisfy the search criteria.
    pub fn new() -> SearchLoyaltyAccountsResponse {
        SearchLoyaltyAccountsResponse {
            errors: None,
            loyalty_accounts: None,
            cursor: None,
        }
    }
}

