/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchCatalogItemsRequest : Defines the request body for the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems) endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchCatalogItemsRequest {
    /// The text filter expression to return items or item variations containing specified text in the `name`, `description`, or `abbreviation` attribute value of an item, or in the `name`, `sku`, or `upc` attribute value of an item variation.
    #[serde(rename = "text_filter", skip_serializing_if = "Option::is_none")]
    pub text_filter: Option<String>,
    /// The category id query expression to return items containing the specified category IDs.
    #[serde(rename = "category_ids", skip_serializing_if = "Option::is_none")]
    pub category_ids: Option<Vec<String>>,
    /// The stock-level query expression to return item variations with the specified stock levels. See [SearchCatalogItemsRequestStockLevel](#type-searchcatalogitemsrequeststocklevel) for possible values
    #[serde(rename = "stock_levels", skip_serializing_if = "Option::is_none")]
    pub stock_levels: Option<Vec<models::SearchCatalogItemsRequestStockLevel>>,
    /// The enabled-location query expression to return items and item variations having specified enabled locations.
    #[serde(rename = "enabled_location_ids", skip_serializing_if = "Option::is_none")]
    pub enabled_location_ids: Option<Vec<String>>,
    /// The pagination token, returned in the previous response, used to fetch the next batch of pending results.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// The maximum number of results to return per page. The default value is 100.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<models::SortOrder>,
    /// The product types query expression to return items or item variations having the specified product types.
    #[serde(rename = "product_types", skip_serializing_if = "Option::is_none")]
    pub product_types: Option<Vec<models::CatalogItemProductType>>,
    /// The customer-attribute filter to return items or item variations matching the specified custom attribute expressions. A maximum number of 10 custom attribute expressions are supported in a single call to the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems) endpoint.
    #[serde(rename = "custom_attribute_filters", skip_serializing_if = "Option::is_none")]
    pub custom_attribute_filters: Option<Vec<models::CustomAttributeFilter>>,
    #[serde(rename = "archived_state", skip_serializing_if = "Option::is_none")]
    pub archived_state: Option<models::ArchivedState>,
}

impl SearchCatalogItemsRequest {
    /// Defines the request body for the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems) endpoint.
    pub fn new() -> SearchCatalogItemsRequest {
        SearchCatalogItemsRequest {
            text_filter: None,
            category_ids: None,
            stock_levels: None,
            enabled_location_ids: None,
            cursor: None,
            limit: None,
            sort_order: None,
            product_types: None,
            custom_attribute_filters: None,
            archived_state: None,
        }
    }
}

