/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchLoyaltyEventsRequest : A request to search for loyalty events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchLoyaltyEventsRequest {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::LoyaltyEventQuery>>,
    /// The maximum number of results to include in the response.  The last page might contain fewer events.  The default is 30 events.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query. For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchLoyaltyEventsRequest {
    /// A request to search for loyalty events.
    pub fn new() -> SearchLoyaltyEventsRequest {
        SearchLoyaltyEventsRequest {
            query: None,
            limit: None,
            cursor: None,
        }
    }
}

