/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchLoyaltyRewardsResponse : A response that includes the loyalty rewards satisfying the search criteria.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchLoyaltyRewardsResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// The loyalty rewards that satisfy the search criteria. These are returned in descending order by `updated_at`.
    #[serde(rename = "rewards", skip_serializing_if = "Option::is_none")]
    pub rewards: Option<Vec<models::LoyaltyReward>>,
    /// The pagination cursor to be used in a subsequent  request. If empty, this is the final response.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl SearchLoyaltyRewardsResponse {
    /// A response that includes the loyalty rewards satisfying the search criteria.
    pub fn new() -> SearchLoyaltyRewardsResponse {
        SearchLoyaltyRewardsResponse {
            errors: None,
            rewards: None,
            cursor: None,
        }
    }
}

