/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchScheduledShiftsResponse : Represents a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) response. Either `scheduled_shifts` or `errors` is present in the response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchScheduledShiftsResponse {
    /// A paginated list of scheduled shifts that match the query conditions.
    #[serde(rename = "scheduled_shifts", skip_serializing_if = "Option::is_none")]
    pub scheduled_shifts: Option<Vec<models::ScheduledShift>>,
    /// The pagination cursor used to retrieve the next page of results. This field is present only if additional results are available.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
}

impl SearchScheduledShiftsResponse {
    /// Represents a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts) response. Either `scheduled_shifts` or `errors` is present in the response.
    pub fn new() -> SearchScheduledShiftsResponse {
        SearchScheduledShiftsResponse {
            scheduled_shifts: None,
            cursor: None,
            errors: None,
        }
    }
}

