/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShiftWorkdayMatcher : Defines the logic used to apply a workday filter.
/// Defines the logic used to apply a workday filter.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShiftWorkdayMatcher {
    #[serde(rename = "START_AT")]
    StartAt,
    #[serde(rename = "END_AT")]
    EndAt,
    #[serde(rename = "INTERSECTION")]
    Intersection,

}

impl std::fmt::Display for ShiftWorkdayMatcher {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StartAt => write!(f, "START_AT"),
            Self::EndAt => write!(f, "END_AT"),
            Self::Intersection => write!(f, "INTERSECTION"),
        }
    }
}

impl Default for ShiftWorkdayMatcher {
    fn default() -> ShiftWorkdayMatcher {
        Self::StartAt
    }
}

