/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignatureOptions {
    /// The title text to display in the signature capture flow on the Terminal.
    #[serde(rename = "title")]
    pub title: String,
    /// The body text to display in the signature capture flow on the Terminal.
    #[serde(rename = "body")]
    pub body: String,
    /// An image representation of the collected signature.
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Vec<models::SignatureImage>>,
}

impl SignatureOptions {
    pub fn new(title: String, body: String) -> SignatureOptions {
        SignatureOptions {
            title,
            body,
            signature: None,
        }
    }
}

