/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SourceApplication : Represents information about the application used to generate a change.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceApplication {
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<models::Product>,
    /// __Read only__ The Square-assigned ID of the application. This field is used only if the [product](entity:Product) type is `EXTERNAL_API`.
    #[serde(rename = "application_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<Option<String>>,
    /// __Read only__ The display name of the application (for example, `\"Custom Application\"` or `\"Square POS 4.74 for Android\"`).
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl SourceApplication {
    /// Represents information about the application used to generate a change.
    pub fn new() -> SourceApplication {
        SourceApplication {
            product: None,
            application_id: None,
            name: None,
        }
    }
}

