/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StandardUnitDescriptionGroup : Group of standard measurement units.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardUnitDescriptionGroup {
    /// List of standard (non-custom) measurement units in this description group.
    #[serde(rename = "standard_unit_descriptions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_unit_descriptions: Option<Option<Vec<models::StandardUnitDescription>>>,
    /// IETF language tag.
    #[serde(rename = "language_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_code: Option<Option<String>>,
}

impl StandardUnitDescriptionGroup {
    /// Group of standard measurement units.
    pub fn new() -> StandardUnitDescriptionGroup {
        StandardUnitDescriptionGroup {
            standard_unit_descriptions: None,
            language_code: None,
        }
    }
}

