/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StandardUnitDescription : Contains the name and abbreviation for standard measurement unit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardUnitDescription {
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Box<models::MeasurementUnit>>,
    /// UI display name of the measurement unit. For example, 'Pound'.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// UI display abbreviation for the measurement unit. For example, 'lb'.
    #[serde(rename = "abbreviation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub abbreviation: Option<Option<String>>,
}

impl StandardUnitDescription {
    /// Contains the name and abbreviation for standard measurement unit.
    pub fn new() -> StandardUnitDescription {
        StandardUnitDescription {
            unit: None,
            name: None,
            abbreviation: None,
        }
    }
}

