/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaxIds : Identifiers for the location used by various governments for tax purposes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaxIds {
    /// The EU VAT number for this location. For example, `IE3426675K`. If the EU VAT number is present, it is well-formed and has been validated with VIES, the VAT Information Exchange System.
    #[serde(rename = "eu_vat", skip_serializing_if = "Option::is_none")]
    pub eu_vat: Option<String>,
    /// The SIRET (Système d'Identification du Répertoire des Entreprises et de leurs Etablissements) number is a 14-digit code issued by the French INSEE. For example, `39922799000021`.
    #[serde(rename = "fr_siret", skip_serializing_if = "Option::is_none")]
    pub fr_siret: Option<String>,
    /// The French government uses the NAF (Nomenclature des Activités Françaises) to display and track economic statistical data. This is also called the APE (Activite Principale de l’Entreprise) code. For example, `6910Z`.
    #[serde(rename = "fr_naf", skip_serializing_if = "Option::is_none")]
    pub fr_naf: Option<String>,
    /// The NIF (Numero de Identificacion Fiscal) number is a nine-character tax identifier used in Spain. If it is present, it has been validated. For example, `73628495A`.
    #[serde(rename = "es_nif", skip_serializing_if = "Option::is_none")]
    pub es_nif: Option<String>,
    /// The QII (Qualified Invoice Issuer) number is a 14-character tax identifier used in Japan. For example, `T1234567890123`.
    #[serde(rename = "jp_qii", skip_serializing_if = "Option::is_none")]
    pub jp_qii: Option<String>,
}

impl TaxIds {
    /// Identifiers for the location used by various governments for tax purposes.
    pub fn new() -> TaxIds {
        TaxIds {
            eu_vat: None,
            fr_siret: None,
            fr_naf: None,
            es_nif: None,
            jp_qii: None,
        }
    }
}

