/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMemberInvitationStatus : Enumerates the possible invitation statuses the team member can have within a business.
/// Enumerates the possible invitation statuses the team member can have within a business.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamMemberInvitationStatus {
    #[serde(rename = "UNINVITED")]
    Uninvited,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "ACCEPTED")]
    Accepted,

}

impl std::fmt::Display for TeamMemberInvitationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Uninvited => write!(f, "UNINVITED"),
            Self::Pending => write!(f, "PENDING"),
            Self::Accepted => write!(f, "ACCEPTED"),
        }
    }
}

impl Default for TeamMemberInvitationStatus {
    fn default() -> TeamMemberInvitationStatus {
        Self::Uninvited
    }
}

