/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMemberAssignedLocationsAssignmentType : Enumerates the possible assignment types that the team member can have.
/// Enumerates the possible assignment types that the team member can have.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TeamMemberAssignedLocationsAssignmentType {
    #[serde(rename = "ALL_CURRENT_AND_FUTURE_LOCATIONS")]
    AllCurrentAndFutureLocations,
    #[serde(rename = "EXPLICIT_LOCATIONS")]
    ExplicitLocations,

}

impl std::fmt::Display for TeamMemberAssignedLocationsAssignmentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AllCurrentAndFutureLocations => write!(f, "ALL_CURRENT_AND_FUTURE_LOCATIONS"),
            Self::ExplicitLocations => write!(f, "EXPLICIT_LOCATIONS"),
        }
    }
}

impl Default for TeamMemberAssignedLocationsAssignmentType {
    fn default() -> TeamMemberAssignedLocationsAssignmentType {
        Self::AllCurrentAndFutureLocations
    }
}

