/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMemberWage : Job and wage information for a [team member](entity:TeamMember). This convenience object provides details needed to specify the `wage` field for a [timecard](entity:Timecard).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMemberWage {
    /// The UUID for this object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The `TeamMember` that this wage is assigned to.
    #[serde(rename = "team_member_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub team_member_id: Option<Option<String>>,
    /// The job title that this wage relates to.
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "hourly_rate", skip_serializing_if = "Option::is_none")]
    pub hourly_rate: Option<Box<models::Money>>,
    /// An identifier for the [job](entity:Job) that this wage relates to.
    #[serde(rename = "job_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<Option<String>>,
    /// Whether team members are eligible for tips when working this job.
    #[serde(rename = "tip_eligible", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tip_eligible: Option<Option<bool>>,
}

impl TeamMemberWage {
    /// Job and wage information for a [team member](entity:TeamMember). This convenience object provides details needed to specify the `wage` field for a [timecard](entity:Timecard).
    pub fn new() -> TeamMemberWage {
        TeamMemberWage {
            id: None,
            team_member_id: None,
            title: None,
            hourly_rate: None,
            job_id: None,
            tip_eligible: None,
        }
    }
}

