/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMemberWageSettingUpdatedEventObject {
    #[serde(rename = "wage_setting", skip_serializing_if = "Option::is_none")]
    pub wage_setting: Option<Box<models::WageSetting>>,
}

impl TeamMemberWageSettingUpdatedEventObject {
    pub fn new() -> TeamMemberWageSettingUpdatedEventObject {
        TeamMemberWageSettingUpdatedEventObject {
            wage_setting: None,
        }
    }
}

