/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TenderCashDetails : Represents the details of a tender with `type` `CASH`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenderCashDetails {
    #[serde(rename = "buyer_tendered_money", skip_serializing_if = "Option::is_none")]
    pub buyer_tendered_money: Option<Box<models::Money>>,
    #[serde(rename = "change_back_money", skip_serializing_if = "Option::is_none")]
    pub change_back_money: Option<Box<models::Money>>,
}

impl TenderCashDetails {
    /// Represents the details of a tender with `type` `CASH`.
    pub fn new() -> TenderCashDetails {
        TenderCashDetails {
            buyer_tendered_money: None,
            change_back_money: None,
        }
    }
}

