/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TerminalActionUpdatedEvent : Published when a TerminalAction is updated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerminalActionUpdatedEvent {
    /// The ID of the target merchant associated with the event.
    #[serde(rename = "merchant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub merchant_id: Option<Option<String>>,
    /// The type of event this represents, `\"terminal.action.updated\"`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// A unique ID for the event.
    #[serde(rename = "event_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<Option<String>>,
    /// RFC 3339 timestamp of when the event was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::TerminalActionUpdatedEventData>>,
}

impl TerminalActionUpdatedEvent {
    /// Published when a TerminalAction is updated.
    pub fn new() -> TerminalActionUpdatedEvent {
        TerminalActionUpdatedEvent {
            merchant_id: None,
            r#type: None,
            event_id: None,
            created_at: None,
            data: None,
        }
    }
}

