/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeRange : Represents a generic time range. The start and end values are represented in RFC 3339 format. Time ranges are customized to be inclusive or exclusive based on the needs of a particular endpoint. Refer to the relevant endpoint-specific documentation to determine how time ranges are handled.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeRange {
    /// A datetime value in RFC 3339 format indicating when the time range starts.
    #[serde(rename = "start_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<Option<String>>,
    /// A datetime value in RFC 3339 format indicating when the time range ends.
    #[serde(rename = "end_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<Option<String>>,
}

impl TimeRange {
    /// Represents a generic time range. The start and end values are represented in RFC 3339 format. Time ranges are customized to be inclusive or exclusive based on the needs of a particular endpoint. Refer to the relevant endpoint-specific documentation to determine how time ranges are handled.
    pub fn new() -> TimeRange {
        TimeRange {
            start_at: None,
            end_at: None,
        }
    }
}

