/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferOrderStatus : Status values for transfer orders. Represents the current state of a  [TransferOrder](entity:TransferOrder) in its lifecycle from creation to completion. Each status determines what actions are available and how inventory is affected.
/// Status values for transfer orders. Represents the current state of a  [TransferOrder](entity:TransferOrder) in its lifecycle from creation to completion. Each status determines what actions are available and how inventory is affected.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferOrderStatus {
    #[serde(rename = "DRAFT")]
    Draft,
    #[serde(rename = "STARTED")]
    Started,
    #[serde(rename = "PARTIALLY_RECEIVED")]
    PartiallyReceived,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "CANCELED")]
    Canceled,

}

impl std::fmt::Display for TransferOrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Draft => write!(f, "DRAFT"),
            Self::Started => write!(f, "STARTED"),
            Self::PartiallyReceived => write!(f, "PARTIALLY_RECEIVED"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Canceled => write!(f, "CANCELED"),
        }
    }
}

impl Default for TransferOrderStatus {
    fn default() -> TransferOrderStatus {
        Self::Draft
    }
}

