/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionProduct : Indicates the Square product used to process a transaction.
/// Indicates the Square product used to process a transaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionProduct {
    #[serde(rename = "REGISTER")]
    Register,
    #[serde(rename = "EXTERNAL_API")]
    ExternalApi,
    #[serde(rename = "BILLING")]
    Billing,
    #[serde(rename = "APPOINTMENTS")]
    Appointments,
    #[serde(rename = "INVOICES")]
    Invoices,
    #[serde(rename = "ONLINE_STORE")]
    OnlineStore,
    #[serde(rename = "PAYROLL")]
    Payroll,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for TransactionProduct {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Register => write!(f, "REGISTER"),
            Self::ExternalApi => write!(f, "EXTERNAL_API"),
            Self::Billing => write!(f, "BILLING"),
            Self::Appointments => write!(f, "APPOINTMENTS"),
            Self::Invoices => write!(f, "INVOICES"),
            Self::OnlineStore => write!(f, "ONLINE_STORE"),
            Self::Payroll => write!(f, "PAYROLL"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for TransactionProduct {
    fn default() -> TransactionProduct {
        Self::Register
    }
}

