/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferOrderFilter : Filter criteria for searching transfer orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferOrderFilter {
    /// Filter by source location IDs
    #[serde(rename = "source_location_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_location_ids: Option<Option<Vec<String>>>,
    /// Filter by destination location IDs
    #[serde(rename = "destination_location_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destination_location_ids: Option<Option<Vec<String>>>,
    /// Filter by order statuses See [TransferOrderStatus](#type-transferorderstatus) for possible values
    #[serde(rename = "statuses", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<Option<Vec<models::TransferOrderStatus>>>,
}

impl TransferOrderFilter {
    /// Filter criteria for searching transfer orders
    pub fn new() -> TransferOrderFilter {
        TransferOrderFilter {
            source_location_ids: None,
            destination_location_ids: None,
            statuses: None,
        }
    }
}

