/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferOrderLine : Represents a line item in a transfer order. Each line item tracks a specific  [CatalogItemVariation](entity:CatalogItemVariation) being transferred, including ordered quantities and receipt status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferOrderLine {
    /// Unique system-generated identifier for the line item. Provide when updating/removing a line via [UpdateTransferOrder](api-endpoint:TransferOrders-UpdateTransferOrder).
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
    /// The required identifier of the [CatalogItemVariation](entity:CatalogItemVariation) being transferred. Must reference a valid catalog item variation that exists in the [Catalog](api:Catalog).
    #[serde(rename = "item_variation_id")]
    pub item_variation_id: String,
    /// Total quantity ordered, formatted as a decimal string (e.g. \"10 or 10.0000\"). Required to be a positive number.  To remove a line item, set `remove` to `true` in [UpdateTransferOrder](api-endpoint:TransferOrders-UpdateTransferOrder).
    #[serde(rename = "quantity_ordered")]
    pub quantity_ordered: String,
    /// Calculated quantity of this line item's yet to be received stock. This is the difference between the total quantity ordered and the sum of quantities received, canceled, and damaged.
    #[serde(rename = "quantity_pending", skip_serializing_if = "Option::is_none")]
    pub quantity_pending: Option<String>,
    /// Quantity received at destination. These items are added to the destination [Location](entity:Location)'s inventory with [InventoryState](entity:InventoryState) of IN_STOCK.  This field cannot be updated directly in Create/Update operations, instead use [ReceiveTransferOrder](api-endpoint:TransferOrders-ReceiveTransferOrder).
    #[serde(rename = "quantity_received", skip_serializing_if = "Option::is_none")]
    pub quantity_received: Option<String>,
    /// Quantity received in damaged condition. These items are added to the destination [Location](entity:Location)'s inventory with [InventoryState](entity:InventoryState) of WASTE.  This field cannot be updated directly in Create/Update operations, instead use [ReceiveTransferOrder](api-endpoint:TransferOrders-ReceiveTransferOrder).
    #[serde(rename = "quantity_damaged", skip_serializing_if = "Option::is_none")]
    pub quantity_damaged: Option<String>,
    /// Quantity that was canceled. These items will be immediately added to inventory in the source location.  This field cannot be updated directly in Create/Update operations, instead use [ReceiveTransferOrder](api-endpoint:TransferOrders-ReceiveTransferOrder) or [CancelTransferOrder](api-endpoint:TransferOrders-CancelTransferOrder).
    #[serde(rename = "quantity_canceled", skip_serializing_if = "Option::is_none")]
    pub quantity_canceled: Option<String>,
}

impl TransferOrderLine {
    /// Represents a line item in a transfer order. Each line item tracks a specific  [CatalogItemVariation](entity:CatalogItemVariation) being transferred, including ordered quantities and receipt status.
    pub fn new(item_variation_id: String, quantity_ordered: String) -> TransferOrderLine {
        TransferOrderLine {
            uid: None,
            item_variation_id,
            quantity_ordered,
            quantity_pending: None,
            quantity_received: None,
            quantity_damaged: None,
            quantity_canceled: None,
        }
    }
}

