/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateCustomerRequest : Defines the body parameters that can be included in a request to the `UpdateCustomer` endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCustomerRequest {
    /// The given name (that is, the first name) associated with the customer profile.  The maximum length for this value is 300 characters.
    #[serde(rename = "given_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub given_name: Option<Option<String>>,
    /// The family name (that is, the last name) associated with the customer profile.  The maximum length for this value is 300 characters.
    #[serde(rename = "family_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub family_name: Option<Option<String>>,
    /// A business name associated with the customer profile.  The maximum length for this value is 500 characters.
    #[serde(rename = "company_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<Option<String>>,
    /// A nickname for the customer profile.  The maximum length for this value is 100 characters.
    #[serde(rename = "nickname", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<Option<String>>,
    /// The email address associated with the customer profile.  The maximum length for this value is 254 characters.
    #[serde(rename = "email_address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<Option<String>>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::Address>>,
    /// The phone number associated with the customer profile. The phone number must be valid and can contain 9–16 digits, with an optional `+` prefix and country code. For more information, see [Customer phone numbers](https://developer.squareup.com/docs/customers-api/use-the-api/keep-records#phone-number).
    #[serde(rename = "phone_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Option<String>>,
    /// An optional second ID used to associate the customer profile with an entity in another system.  The maximum length for this value is 100 characters.
    #[serde(rename = "reference_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Option<String>>,
    /// A custom note associated with the customer profile.
    #[serde(rename = "note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub note: Option<Option<String>>,
    /// The birthday associated with the customer profile, in `YYYY-MM-DD` or `MM-DD` format. For example, specify `1998-09-21` for September 21, 1998, or `09-21` for September 21. Birthdays are returned in `YYYY-MM-DD` format, where `YYYY` is the specified birth year or `0000` if a birth year is not specified.
    #[serde(rename = "birthday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birthday: Option<Option<String>>,
    /// The current version of the customer profile.  As a best practice, you should include this field to enable [optimistic concurrency](https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency) control. For more information, see [Update a customer profile](https://developer.squareup.com/docs/customers-api/use-the-api/keep-records#update-a-customer-profile).
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
    #[serde(rename = "tax_ids", skip_serializing_if = "Option::is_none")]
    pub tax_ids: Option<Box<models::CustomerTaxIds>>,
}

impl UpdateCustomerRequest {
    /// Defines the body parameters that can be included in a request to the `UpdateCustomer` endpoint.
    pub fn new() -> UpdateCustomerRequest {
        UpdateCustomerRequest {
            given_name: None,
            family_name: None,
            company_name: None,
            nickname: None,
            email_address: None,
            address: None,
            phone_number: None,
            reference_id: None,
            note: None,
            birthday: None,
            version: None,
            tax_ids: None,
        }
    }
}

