/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdatePaymentRequest : Describes a request to update a payment using [UpdatePayment](api-endpoint:Payments-UpdatePayment).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePaymentRequest {
    #[serde(rename = "payment", skip_serializing_if = "Option::is_none")]
    pub payment: Option<Box<models::Payment>>,
    /// A unique string that identifies this `UpdatePayment` request. Keys can be any valid string but must be unique for every `UpdatePayment` request.  For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
}

impl UpdatePaymentRequest {
    /// Describes a request to update a payment using [UpdatePayment](api-endpoint:Payments-UpdatePayment).
    pub fn new(idempotency_key: String) -> UpdatePaymentRequest {
        UpdatePaymentRequest {
            payment: None,
            idempotency_key,
        }
    }
}

