/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateTransferOrderRequest : Request to update a transfer order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTransferOrderRequest {
    /// A unique string that identifies this UpdateTransferOrder request. Keys must contain only alphanumeric characters, dashes and underscores
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    #[serde(rename = "transfer_order")]
    pub transfer_order: Box<models::UpdateTransferOrderData>,
    /// Version for optimistic concurrency
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
}

impl UpdateTransferOrderRequest {
    /// Request to update a transfer order
    pub fn new(idempotency_key: String, transfer_order: models::UpdateTransferOrderData) -> UpdateTransferOrderRequest {
        UpdateTransferOrderRequest {
            idempotency_key,
            transfer_order: Box::new(transfer_order),
            version: None,
        }
    }
}

