/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateCustomerGroupResponse : Defines the fields that are included in the response body of a request to the [UpdateCustomerGroup](api-endpoint:CustomerGroups-UpdateCustomerGroup) endpoint.  Either `errors` or `group` is present in a given response (never both).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCustomerGroupResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::CustomerGroup>>,
}

impl UpdateCustomerGroupResponse {
    /// Defines the fields that are included in the response body of a request to the [UpdateCustomerGroup](api-endpoint:CustomerGroups-UpdateCustomerGroup) endpoint.  Either `errors` or `group` is present in a given response (never both).
    pub fn new() -> UpdateCustomerGroupResponse {
        UpdateCustomerGroupResponse {
            errors: None,
            group: None,
        }
    }
}

