/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateWageSettingRequest : Represents an update request for the `WageSetting` object describing a `TeamMember`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWageSettingRequest {
    #[serde(rename = "wage_setting")]
    pub wage_setting: Box<models::WageSetting>,
}

impl UpdateWageSettingRequest {
    /// Represents an update request for the `WageSetting` object describing a `TeamMember`.
    pub fn new(wage_setting: models::WageSetting) -> UpdateWageSettingRequest {
        UpdateWageSettingRequest {
            wage_setting: Box::new(wage_setting),
        }
    }
}

