/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBookingRequest {
    /// A unique key to make this request an idempotent operation.
    #[serde(rename = "idempotency_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<Option<String>>,
    #[serde(rename = "booking")]
    pub booking: Box<models::Booking>,
}

impl UpdateBookingRequest {
    pub fn new(booking: models::Booking) -> UpdateBookingRequest {
        UpdateBookingRequest {
            idempotency_key: None,
            booking: Box::new(booking),
        }
    }
}

