/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateWebhookSubscriptionResponse : Defines the fields that are included in the response body of a request to the [UpdateWebhookSubscription](api-endpoint:WebhookSubscriptions-UpdateWebhookSubscription) endpoint.  Note: If there are errors processing the request, the [Subscription](entity:WebhookSubscription) is not present.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebhookSubscriptionResponse {
    /// Information on errors encountered during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "subscription", skip_serializing_if = "Option::is_none")]
    pub subscription: Option<Box<models::WebhookSubscription>>,
}

impl UpdateWebhookSubscriptionResponse {
    /// Defines the fields that are included in the response body of a request to the [UpdateWebhookSubscription](api-endpoint:WebhookSubscriptions-UpdateWebhookSubscription) endpoint.  Note: If there are errors processing the request, the [Subscription](entity:WebhookSubscription) is not present.
    pub fn new() -> UpdateWebhookSubscriptionResponse {
        UpdateWebhookSubscriptionResponse {
            errors: None,
            subscription: None,
        }
    }
}

