/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdatePaymentResponse : Defines the response returned by [UpdatePayment](api-endpoint:Payments-UpdatePayment).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePaymentResponse {
    /// Any errors that occurred during the request.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    #[serde(rename = "payment", skip_serializing_if = "Option::is_none")]
    pub payment: Option<Box<models::Payment>>,
}

impl UpdatePaymentResponse {
    /// Defines the response returned by [UpdatePayment](api-endpoint:Payments-UpdatePayment).
    pub fn new() -> UpdatePaymentResponse {
        UpdatePaymentResponse {
            errors: None,
            payment: None,
        }
    }
}

