/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpsertSnippetRequest : Represents an `UpsertSnippet` request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertSnippetRequest {
    #[serde(rename = "snippet")]
    pub snippet: Box<models::Snippet>,
}

impl UpsertSnippetRequest {
    /// Represents an `UpsertSnippet` request.
    pub fn new(snippet: models::Snippet) -> UpsertSnippetRequest {
        UpsertSnippetRequest {
            snippet: Box::new(snippet),
        }
    }
}

