/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1OrderHistoryEntryAction {
    #[serde(rename = "ORDER_PLACED")]
    OrderPlaced,
    #[serde(rename = "DECLINED")]
    Declined,
    #[serde(rename = "PAYMENT_RECEIVED")]
    PaymentReceived,
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "REFUNDED")]
    Refunded,
    #[serde(rename = "EXPIRED")]
    Expired,

}

impl std::fmt::Display for V1OrderHistoryEntryAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OrderPlaced => write!(f, "ORDER_PLACED"),
            Self::Declined => write!(f, "DECLINED"),
            Self::PaymentReceived => write!(f, "PAYMENT_RECEIVED"),
            Self::Canceled => write!(f, "CANCELED"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Refunded => write!(f, "REFUNDED"),
            Self::Expired => write!(f, "EXPIRED"),
        }
    }
}

impl Default for V1OrderHistoryEntryAction {
    fn default() -> V1OrderHistoryEntryAction {
        Self::OrderPlaced
    }
}

