/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: developers@squareup.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VendorUpdatedEventData : Defines the `vendor.updated` event data structure.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VendorUpdatedEventData {
    /// The type of the event data object. The value is `vendor`.
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    /// The ID of the event data object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Box<models::VendorUpdatedEventObject>>,
}

impl VendorUpdatedEventData {
    /// Defines the `vendor.updated` event data structure.
    pub fn new() -> VendorUpdatedEventData {
        VendorUpdatedEventData {
            r#type: None,
            id: None,
            object: None,
        }
    }
}

